/// Auto-generated from Modifiers.fs
/// Pure string values for use with Fable.React, Giraffe, and SSR scenarios
/// where Feliz's prop.className is not available.
namespace Feliz.Tailwind

[<AutoOpen>]
module Strings =

    /// Combines multiple Tailwind class names into a single string
    let tw (classes: string list) =
        classes
        |> List.filter (System.String.IsNullOrWhiteSpace >> not)
        |> String.concat " "

    /// backgroundColor utilities
    module backgroundColor =
        let bgBlack = "bg-black"
        let bgWhite = "bg-white"
        let bgRed50 = "bg-red-50"
        let bgRed100 = "bg-red-100"
        let bgRed200 = "bg-red-200"
        let bgRed300 = "bg-red-300"
        let bgRed400 = "bg-red-400"
        let bgRed500 = "bg-red-500"
        let bgRed600 = "bg-red-600"
        let bgRed700 = "bg-red-700"
        let bgRed800 = "bg-red-800"
        let bgRed900 = "bg-red-900"
        let bgRed950 = "bg-red-950"
        let bgOrange50 = "bg-orange-50"
        let bgOrange100 = "bg-orange-100"
        let bgOrange200 = "bg-orange-200"
        let bgOrange300 = "bg-orange-300"
        let bgOrange400 = "bg-orange-400"
        let bgOrange500 = "bg-orange-500"
        let bgOrange600 = "bg-orange-600"
        let bgOrange700 = "bg-orange-700"
        let bgOrange800 = "bg-orange-800"
        let bgOrange900 = "bg-orange-900"
        let bgOrange950 = "bg-orange-950"
        let bgAmber50 = "bg-amber-50"
        let bgAmber100 = "bg-amber-100"
        let bgAmber200 = "bg-amber-200"
        let bgAmber300 = "bg-amber-300"
        let bgAmber400 = "bg-amber-400"
        let bgAmber500 = "bg-amber-500"
        let bgAmber600 = "bg-amber-600"
        let bgAmber700 = "bg-amber-700"
        let bgAmber800 = "bg-amber-800"
        let bgAmber900 = "bg-amber-900"
        let bgAmber950 = "bg-amber-950"
        let bgYellow50 = "bg-yellow-50"
        let bgYellow100 = "bg-yellow-100"
        let bgYellow200 = "bg-yellow-200"
        let bgYellow300 = "bg-yellow-300"
        let bgYellow400 = "bg-yellow-400"
        let bgYellow500 = "bg-yellow-500"
        let bgYellow600 = "bg-yellow-600"
        let bgYellow700 = "bg-yellow-700"
        let bgYellow800 = "bg-yellow-800"
        let bgYellow900 = "bg-yellow-900"
        let bgYellow950 = "bg-yellow-950"
        let bgLime50 = "bg-lime-50"
        let bgLime100 = "bg-lime-100"
        let bgLime200 = "bg-lime-200"
        let bgLime300 = "bg-lime-300"
        let bgLime400 = "bg-lime-400"
        let bgLime500 = "bg-lime-500"
        let bgLime600 = "bg-lime-600"
        let bgLime700 = "bg-lime-700"
        let bgLime800 = "bg-lime-800"
        let bgLime900 = "bg-lime-900"
        let bgLime950 = "bg-lime-950"
        let bgGreen50 = "bg-green-50"
        let bgGreen100 = "bg-green-100"
        let bgGreen200 = "bg-green-200"
        let bgGreen300 = "bg-green-300"
        let bgGreen400 = "bg-green-400"
        let bgGreen500 = "bg-green-500"
        let bgGreen600 = "bg-green-600"
        let bgGreen700 = "bg-green-700"
        let bgGreen800 = "bg-green-800"
        let bgGreen900 = "bg-green-900"
        let bgGreen950 = "bg-green-950"
        let bgEmerald50 = "bg-emerald-50"
        let bgEmerald100 = "bg-emerald-100"
        let bgEmerald200 = "bg-emerald-200"
        let bgEmerald300 = "bg-emerald-300"
        let bgEmerald400 = "bg-emerald-400"
        let bgEmerald500 = "bg-emerald-500"
        let bgEmerald600 = "bg-emerald-600"
        let bgEmerald700 = "bg-emerald-700"
        let bgEmerald800 = "bg-emerald-800"
        let bgEmerald900 = "bg-emerald-900"
        let bgEmerald950 = "bg-emerald-950"
        let bgTeal50 = "bg-teal-50"
        let bgTeal100 = "bg-teal-100"
        let bgTeal200 = "bg-teal-200"
        let bgTeal300 = "bg-teal-300"
        let bgTeal400 = "bg-teal-400"
        let bgTeal500 = "bg-teal-500"
        let bgTeal600 = "bg-teal-600"
        let bgTeal700 = "bg-teal-700"
        let bgTeal800 = "bg-teal-800"
        let bgTeal900 = "bg-teal-900"
        let bgTeal950 = "bg-teal-950"
        let bgCyan50 = "bg-cyan-50"
        let bgCyan100 = "bg-cyan-100"
        let bgCyan200 = "bg-cyan-200"
        let bgCyan300 = "bg-cyan-300"
        let bgCyan400 = "bg-cyan-400"
        let bgCyan500 = "bg-cyan-500"
        let bgCyan600 = "bg-cyan-600"
        let bgCyan700 = "bg-cyan-700"
        let bgCyan800 = "bg-cyan-800"
        let bgCyan900 = "bg-cyan-900"
        let bgCyan950 = "bg-cyan-950"
        let bgSky50 = "bg-sky-50"
        let bgSky100 = "bg-sky-100"
        let bgSky200 = "bg-sky-200"
        let bgSky300 = "bg-sky-300"
        let bgSky400 = "bg-sky-400"
        let bgSky500 = "bg-sky-500"
        let bgSky600 = "bg-sky-600"
        let bgSky700 = "bg-sky-700"
        let bgSky800 = "bg-sky-800"
        let bgSky900 = "bg-sky-900"
        let bgSky950 = "bg-sky-950"
        let bgBlue50 = "bg-blue-50"
        let bgBlue100 = "bg-blue-100"
        let bgBlue200 = "bg-blue-200"
        let bgBlue300 = "bg-blue-300"
        let bgBlue400 = "bg-blue-400"
        let bgBlue500 = "bg-blue-500"
        let bgBlue600 = "bg-blue-600"
        let bgBlue700 = "bg-blue-700"
        let bgBlue800 = "bg-blue-800"
        let bgBlue900 = "bg-blue-900"
        let bgBlue950 = "bg-blue-950"
        let bgSlate100 = "bg-slate-100"
        let bgSlate200 = "bg-slate-200"
        let bgSlate300 = "bg-slate-300"
        let bgSlate400 = "bg-slate-400"
        let bgSlate500 = "bg-slate-500"
        let bgSlate600 = "bg-slate-600"
        let bgSlate700 = "bg-slate-700"
        let bgSlate800 = "bg-slate-800"
        let bgSlate900 = "bg-slate-900"
        let bgSlate950 = "bg-slate-950"

    /// borderRadius utilities
    module borderRadius =
        let roundedNone = "rounded-none"
        let roundedSm = "rounded-sm"
        let rounded = "rounded"
        let roundedMd = "rounded-md"
        let roundedLg = "rounded-lg"
        let roundedXl = "rounded-xl"
        let rounded2Xl = "rounded-2xl"
        let rounded3Xl = "rounded-3xl"

    /// borderWidth utilities
    module borderWidth =
        let borderR = "border-r"
        let borderL = "border-l"
        let borderT = "border-t"
        let borderB = "border-b"

    /// boxShadow utilities
    module boxShadow =
        let shadow2Xs = "shadow-2xs"
        let shadowXs = "shadow-xs"
        let shadowSm = "shadow-sm"
        let shadow = "shadow"
        let shadowMd = "shadow-md"
        let shadowLg = "shadow-lg"
        let shadowXl = "shadow-xl"
        let shadow2Xl = "shadow-2xl"
        let shadowInner = "shadow-inner"
        let shadowNone = "shadow-none"

    /// display utilities
    module display =
        let block = "block"
        let inlineBlock = "inline-block"
        let ``inline'`` = "inline"
        let flex = "flex"
        let inlineFlex = "inline-flex"
        let grid = "grid"
        let inlineGrid = "inline-grid"
        let hidden = "hidden"
        let contents = "contents"
        let flowRoot = "flow-root"
        let table = "table"
        let tableRow = "table-row"
        let tableCell = "table-cell"

    /// flex utilities
    module flex =
        let flex = "flex"
        let flex1 = "flex-1"
        let flexAuto = "flex-auto"
        let flexInitial = "flex-initial"
        let flexNone = "flex-none"
        let flexRow = "flex-row"
        let flexWrap = "flex-wrap"
        let flexWrapReverse = "flex-wrap-reverse"
        let flexNoWrap = "flex-nowrap"
        let flexCol = "flex-col"

    /// flexDirection utilities
    module flexDirection =
        let flexRow = "flex-row"
        let flexRowReserve = "flex-row-reserve"
        let flexCol = "flex-col"
        let flexColReserve = "flex-col-reserve"

    /// flexShrink utilities
    module flexShrink =
        let flexShrink = "flex-shrink"
        let flexShrink0 = "flex-shrink-0"

    /// flexGrow utilities
    module flexGrow =
        let flexGrow = "flex-grow"
        let flexGrow0 = "flex-grow-0"

    /// fontSize utilities
    module fontSize =
        let textXs = "text-xs"
        let textSm = "text-sm"
        let textBase = "text-base"
        let textLg = "text-lg"
        let textXl = "text-xl"
        let text2Xl = "text-2xl"
        let text3Xl = "text-3xl"
        let text4Xl = "text-4xl"
        let text5Xl = "text-5xl"
        let text6Xl = "text-6xl"
        let text7Xl = "text-7xl"
        let text8Xl = "text-8xl"
        let text9Xl = "text-9xl"

    /// fontWeight utilities
    module fontWeight =
        let fontThin = "font-thin"
        let fontExtraLight = "font-extralight"
        let fontLight = "font-light"
        let fontNormal = "font-normal"
        let fontMedium = "font-medium"
        let fontSemibold = "font-semibold"
        let fontBold = "font-bold"
        let fontExtraBold = "font-extrabold"
        let fontBlack = "font-black"

    /// minHeight utilities
    module minHeight =
        let minHAuto = "min-h-auto"
        let minHFull = "min-h-full"
        let minHScreen = "min-h-screen"
        let minHMin = "min-h-min"
        let minHMax = "min-h-max"
        let minHFit = "min-h-fit"

    /// height utilities
    module height =
        let h0 = "h-0"
        let hpx = "h-px"
        let ``h0.5`` = "h-0.5"
        let h1 = "h-1"
        let ``h1.5`` = "h-1.5"
        let h2 = "h-2"
        let ``h2.5`` = "h-2.5"
        let h3 = "h-3"
        let ``h3.5`` = "h-3.5"
        let h4 = "h-4"
        let h5 = "h-5"
        let h6 = "h-6"
        let h7 = "h-7"
        let h8 = "h-8"
        let h9 = "h-9"
        let h10 = "h-10"
        let h11 = "h-11"
        let h12 = "h-12"
        let h14 = "h-14"
        let h16 = "h-16"
        let h20 = "h-20"
        let h24 = "h-24"
        let h28 = "h-28"
        let h32 = "h-32"
        let h36 = "h-36"
        let h40 = "h-40"
        let h44 = "h-44"
        let h48 = "h-48"
        let h52 = "h-52"
        let h56 = "h-56"
        let h60 = "h-60"
        let h64 = "h-64"
        let h72 = "h-72"
        let h80 = "h-80"
        let h96 = "h-96"
        let hAuto = "h-auto"
        let ``h1/2`` = "h-1/2"
        let ``h1/3`` = "h-1/3"
        let ``h2/3`` = "h-2/3"
        let ``h1/4`` = "h-1/4"
        let ``h2/4`` = "h-2/4"
        let ``h3/4`` = "h-3/4"
        let ``h1/5`` = "h-1/5"
        let ``h2/5`` = "h-2/5"
        let ``h3/5`` = "h-3/5"
        let ``h4/5`` = "h-4/5"
        let ``h1/6`` = "h-1/6"
        let ``h2/6`` = "h-2/6"
        let ``h3/6`` = "h-3/6"
        let ``h4/6`` = "h-4/6"
        let ``h5/6`` = "h-5/6"
        let hFull = "h-full"
        let hScreen = "h-screen"
        let hMin = "h-min"
        let hMax = "h-max"
        let hFit = "h-fit"

    /// justifyContent utilities
    module justifyContent =
        let justifyStart = "justify-start"
        let justifyEnd = "justify-end"
        let justifyCenter = "justify-center"
        let justifyBetween = "justify-between"
        let justifyAround = "justify-around"
        let justifyEvenly = "justify-evenly"
        let justifyItemsStart = "justify-items-start"
        let justifyItemsEnd = "justify-items-end"
        let justifyItemsCenter = "justify-items-center"
        let justifyItemsStretch = "justify-items-stretch"
        let justifyItemsBaseline = "justify-items-baseline"

    /// margin utilities
    module margin =
        let m0 = "m-0"
        let mx0 = "mx-0"
        let my0 = "my-0"
        let mt0 = "mt-0"
        let mr0 = "mr-0"
        let mb0 = "mb-0"
        let ml0 = "ml-0"
        let mpx = "m-px"
        let mxpx = "mx-px"
        let mtpx = "mt-px"
        let mrpx = "mr-px"
        let mbpx = "mb-px"
        let mlpx = "ml-px"
        let ``m0.5`` = "m-0.5"
        let ``mx0.5`` = "mx-0.5"
        let ``my0.5`` = "my-0.5"
        let ``mt0.5`` = "mt-0.5"
        let ``mr0.5`` = "mr-0.5"
        let ``mb0.5`` = "mb-0.5"
        let ``ml0.5`` = "ml-0.5"
        let m1 = "m-1"
        let mx1 = "mx-1"
        let my1 = "my-1"
        let mt1 = "mt-1"
        let mr1 = "mr-1"
        let mb1 = "mb-1"
        let ml1 = "ml-1"
        let ``m1.5`` = "m-1.5"
        let ``mx1.5`` = "mx-1.5"
        let ``my1.5`` = "my-1.5"
        let ``mt1.5`` = "mt-1.5"
        let ``mr1.5`` = "mr-1.5"
        let ``mb1.5`` = "mb-1.5"
        let ``ml1.5`` = "ml-1.5"
        let m2 = "m-2"
        let mx2 = "mx-2"
        let my2 = "my-2"
        let mt2 = "mt-2"
        let mr2 = "mr-2"
        let mb2 = "mb-2"
        let ml2 = "ml-2"
        let ``m2.5`` = "m-2.5"
        let ``mx2.5`` = "mx-2.5"
        let ``my2.5`` = "my-2.5"
        let ``mt2.5`` = "mt-2.5"
        let ``mr2.5`` = "mr-2.5"
        let ``mb2.5`` = "mb-2.5"
        let ``ml2.5`` = "ml-2.5"
        let m3 = "m-3"
        let mx3 = "mx-3"
        let my3 = "my-3"
        let mt3 = "mt-3"
        let mr3 = "mr-3"
        let mb3 = "mb-3"
        let ml3 = "ml-3"
        let ``m3.5`` = "m-3.5"
        let ``mx3.5`` = "mx-3.5"
        let ``my3.5`` = "my-3.5"
        let ``mt3.5`` = "mt-3.5"
        let ``mr3.5`` = "mr-3.5"
        let ``mb3.5`` = "mb-3.5"
        let ``ml3.5`` = "ml-3.5"
        let m4 = "m-4"
        let mx4 = "mx-4"
        let my4 = "my-4"
        let mt4 = "mt-4"
        let mr4 = "mr-4"
        let mb4 = "mb-4"
        let ml4 = "ml-4"
        let m5 = "m-5"
        let mx5 = "mx-5"
        let my5 = "my-5"
        let mt5 = "mt-5"
        let mr5 = "mr-5"
        let mb5 = "mb-5"
        let ml5 = "ml-5"
        let m6 = "m-6"
        let mx6 = "mx-6"
        let my6 = "my-6"
        let mt6 = "mt-6"
        let mr6 = "mr-6"
        let mb6 = "mb-6"
        let ml6 = "ml-6"
        let m7 = "m-7"
        let mx7 = "mx-7"
        let my7 = "my-7"
        let mt7 = "mt-7"
        let mr7 = "mr-7"
        let mb7 = "mb-7"
        let ml7 = "ml-7"
        let m8 = "m-8"
        let mx8 = "mx-8"
        let my8 = "my-8"
        let mt8 = "mt-8"
        let mr8 = "mr-8"
        let mb8 = "mb-8"
        let ml8 = "ml-8"
        let m9 = "m-9"
        let mx9 = "mx-9"
        let my9 = "my-9"
        let mt9 = "mt-9"
        let mr9 = "mr-9"
        let mb9 = "mb-9"
        let ml9 = "ml-9"
        let m10 = "m-10"
        let mx10 = "mx-10"
        let my10 = "my-10"
        let mt10 = "mt-10"
        let mr10 = "mr-10"
        let mb10 = "mb-10"
        let ml10 = "ml-10"
        let m11 = "m-11"
        let mx11 = "mx-11"
        let my11 = "my-11"
        let mt11 = "mt-11"
        let mr11 = "mr-11"
        let mb11 = "mb-11"
        let ml11 = "ml-11"
        let m12 = "m-12"
        let mx12 = "mx-12"
        let my12 = "my-12"
        let mt12 = "mt-12"
        let mr12 = "mr-12"
        let mb12 = "mb-12"
        let ml12 = "ml-12"
        let m14 = "m-14"
        let mx14 = "mx-14"
        let my14 = "my-14"
        let mt14 = "mt-14"
        let mr14 = "mr-14"
        let mb14 = "mb-14"
        let ml14 = "ml-14"
        let m16 = "m-16"
        let mx16 = "mx-16"
        let my16 = "my-16"
        let mt16 = "mt-16"
        let mr16 = "mr-16"
        let mb16 = "mb-16"
        let ml16 = "ml-16"
        let m20 = "m-20"
        let mx20 = "mx-20"
        let my20 = "my-20"
        let mt20 = "mt-20"
        let mr20 = "mr-20"
        let mb20 = "mb-20"
        let ml20 = "ml-20"
        let m24 = "m-24"
        let mx24 = "mx-24"
        let my24 = "my-24"
        let mt24 = "mt-24"
        let mr24 = "mr-24"
        let mb24 = "mb-24"
        let ml24 = "ml-24"
        let m28 = "m-28"
        let mx28 = "mx-28"
        let my28 = "my-28"
        let mt28 = "mt-28"
        let mr28 = "mr-28"
        let mb28 = "mb-28"
        let ml28 = "ml-28"
        let m32 = "m-32"
        let mx32 = "mx-32"
        let my32 = "my-32"
        let mt32 = "mt-32"
        let mr32 = "mr-32"
        let mb32 = "mb-32"
        let ml32 = "ml-32"
        let m36 = "m-36"
        let mx36 = "mx-36"
        let my36 = "my-36"
        let mt36 = "mt-36"
        let mr36 = "mr-36"
        let mb36 = "mb-36"
        let ml36 = "ml-36"
        let m40 = "m-40"
        let mx40 = "mx-40"
        let my40 = "my-40"
        let mt40 = "mt-40"
        let mr40 = "mr-40"
        let mb40 = "mb-40"
        let ml40 = "ml-40"
        let m44 = "m-44"
        let mx44 = "mx-44"
        let my44 = "my-44"
        let mt44 = "mt-44"
        let mr44 = "mr-44"
        let mb44 = "mb-44"
        let ml44 = "ml-44"
        let m48 = "m-48"
        let mx48 = "mx-48"
        let my48 = "my-48"
        let mt48 = "mt-48"
        let mr48 = "mr-48"
        let mb48 = "mb-48"
        let ml48 = "ml-48"
        let m52 = "m-52"
        let mx52 = "mx-52"
        let my52 = "my-52"
        let mt52 = "mt-52"
        let mr52 = "mr-52"
        let mb52 = "mb-52"
        let ml52 = "ml-52"
        let m56 = "m-56"
        let mx56 = "mx-56"
        let my56 = "my-56"
        let mt56 = "mt-56"
        let mr56 = "mr-56"
        let mb56 = "mb-56"
        let ml56 = "ml-56"
        let m60 = "m-60"
        let mx60 = "mx-60"
        let my60 = "my-60"
        let mt60 = "mt-60"
        let mr60 = "mr-60"
        let mb60 = "mb-60"
        let ml60 = "ml-60"
        let m64 = "m-64"
        let mx64 = "mx-64"
        let my64 = "my-64"
        let mt64 = "mt-64"
        let mr64 = "mr-64"
        let mb64 = "mb-64"
        let ml64 = "ml-64"
        let m72 = "m-72"
        let mx72 = "mx-72"
        let my72 = "my-72"
        let mt72 = "mt-72"
        let mr72 = "mr-72"
        let mb72 = "mb-72"
        let ml72 = "ml-72"
        let m80 = "m-80"
        let mx80 = "mx-80"
        let my80 = "my-80"
        let mt80 = "mt-80"
        let mr80 = "mr-80"
        let mb80 = "mb-80"
        let ml80 = "ml-80"
        let m96 = "m-96"
        let mx96 = "mx-96"
        let my96 = "my-96"
        let mt96 = "mt-96"
        let mr96 = "mr-96"
        let mb96 = "mb-96"
        let mAuto = "m-auto"
        let mxAuto = "mx-auto"
        let myAuto = "my-auto"
        let mtAuto = "mt-auto"
        let mrAuto = "mr-auto"
        let mbAuto = "mb-auto"
        let mlAuto = "ml-auto"

    /// maxWidth utilities
    module maxWidth =
        let w0 = "max-w-0"
        let wNone = "max-w-none"
        let wXs = "max-w-xs"
        let wSm = "max-w-sm"
        let wMm = "max-w-md"
        let wLg = "max-w-lg"
        let wXl = "max-w-xl"
        let w2Xl = "max-w-2xl"
        let w3Xl = "max-w-3xl"
        let w4Xl = "max-w-4xl"
        let w5Xl = "max-w-5xl"
        let w6Xl = "max-w-6xl"
        let w7Xl = "max-w-7xl"
        let wFull = "max-w-full"
        let wMin = "max-w-min"
        let wMax = "max-w-max"
        let wFit = "max-w-fit"
        let wProse = "max-w-prose"
        let wScreenSm = "max-w-screen-sm"
        let wScreenMd = "max-w-screen-md"
        let wScreenLg = "max-w-screen-lg"
        let wScreenXl = "max-w-screen-xl"
        let wScreen2Xl = "max-w-screen-2xl"

    /// maxHeight utilities
    module maxHeight =
        let h0 = "max-h-0"
        let hPx = "max-h-px"
        let ``h0.5`` = "max-h-0.5"
        let h1 = "max-h-1"
        let ``h1.5`` = "max-h-1.5"
        let h2 = "max-h-2"
        let ``h2.5`` = "max-h-2.5"
        let h3 = "max-h-3"
        let ``h3.5`` = "max-h-3.5"
        let h4 = "max-h-4"
        let h5 = "max-h-5"
        let h6 = "max-h-6"
        let h7 = "max-h-7"
        let h8 = "max-h-8"
        let h9 = "max-h-9"
        let h10 = "max-h-10"
        let h11 = "max-h-11"
        let h12 = "max-h-12"
        let h14 = "max-h-14"
        let h16 = "max-h-16"
        let h20 = "max-h-20"
        let h24 = "max-h-24"
        let h28 = "max-h-28"
        let h32 = "max-h-32"
        let h36 = "max-h-36"
        let h40 = "max-h-40"
        let h44 = "max-h-44"
        let h48 = "max-h-48"
        let h52 = "max-h-52"
        let h56 = "max-h-56"
        let h60 = "max-h-60"
        let h64 = "max-h-64"
        let h72 = "max-h-72"
        let h80 = "max-h-80"
        let h96 = "max-h-96"
        let hFull = "max-h-full"
        let hScreen = "max-h-screen"
        let hMin = "max-h-min"
        let hMax = "max-h-max"
        let hFit = "max-h-fit"

    /// outline utilities
    module outline =
        let outlineNone = "outline-none"
        let outline = "outline"
        let outlineDashed = "outline-dashed"
        let outlineDotted = "outline-dotted"
        let outlineDouble = "outline-double"

    /// overflow utilities
    module overflow =
        let overflowAuto = "overflow-auto"
        let overflowHidden = "overflow-hidden"
        let overflowClip = "overflow-clip"
        let overflowVisible = "overflow-visible"
        let overflowScroll = "overflow-scroll"
        let overflowXAuto = "overflow-x-auto"
        let overflowYAuto = "overflow-y-auto"
        let overflowXHidden = "overflow-x-hidden"

    /// textColor utilities
    module textColor =
        let ``inherit`` = "text-inherit"
        let current = "text-current"
        let transparent = "text-transparent"
        let black = "text-black"
        let white = "text-white"
        let slate50 = "text-slate-50"
        let slate100 = "text-slate-100"
        let slate200 = "text-slate-200"
        let slate300 = "text-slate-300"
        let slate400 = "text-slate-400"
        let slate500 = "text-slate-500"
        let slate600 = "text-slate-600"
        let slate700 = "text-slate-700"
        let slate800 = "text-slate-800"
        let slate900 = "text-slate-900"
        let slate950 = "text-slate-950"
        let gray50 = "text-gray-50"
        let gray100 = "text-gray-100"
        let gray200 = "text-gray-200"
        let gray300 = "text-gray-300"
        let gray400 = "text-gray-400"
        let gray500 = "text-gray-500"
        let gray600 = "text-gray-600"
        let gray700 = "text-gray-700"
        let gray800 = "text-gray-800"
        let gray900 = "text-gray-900"
        let gray950 = "text-gray-950"
        let zinc50 = "text-zinc-50"
        let zinc100 = "text-zinc-100"
        let zinc200 = "text-zinc-200"
        let zinc300 = "text-zinc-300"
        let zinc400 = "text-zinc-400"
        let zinc500 = "text-zinc-500"
        let zinc600 = "text-zinc-600"
        let zinc700 = "text-zinc-700"
        let zinc800 = "text-zinc-800"
        let zinc900 = "text-zinc-900"
        let zinc950 = "text-zinc-950"
        let neutral50 = "text-neutral-50"
        let neutral100 = "text-neutral-100"
        let neutral200 = "text-neutral-200"
        let neutral300 = "text-neutral-300"
        let neutral400 = "text-neutral-400"
        let neutral500 = "text-neutral-500"
        let neutral600 = "text-neutral-600"
        let neutral700 = "text-neutral-700"
        let neutral800 = "text-neutral-800"
        let neutral900 = "text-neutral-900"
        let neutral950 = "text-neutral-950"
        let stone50 = "text-stone-50"
        let stone100 = "text-stone-100"
        let stone200 = "text-stone-200"
        let stone300 = "text-stone-300"
        let stone400 = "text-stone-400"
        let stone500 = "text-stone-500"
        let stone600 = "text-stone-600"
        let stone700 = "text-stone-700"
        let stone800 = "text-stone-800"
        let stone900 = "text-stone-900"
        let stone950 = "text-stone-950"
        let red50 = "text-red-50"
        let red100 = "text-red-100"
        let red200 = "text-red-200"
        let red300 = "text-red-300"
        let red400 = "text-red-400"
        let red500 = "text-red-500"
        let red600 = "text-red-600"
        let red700 = "text-red-700"
        let red800 = "text-red-800"
        let red900 = "text-red-900"
        let red950 = "text-red-950"
        let orange50 = "text-orange-50"
        let orange100 = "text-orange-100"
        let orange200 = "text-orange-200"
        let orange300 = "text-orange-300"
        let orange400 = "text-orange-400"
        let orange500 = "text-orange-500"
        let orange600 = "text-orange-600"
        let orange700 = "text-orange-700"
        let orange800 = "text-orange-800"
        let orange900 = "text-orange-900"
        let orange950 = "text-orange-950"
        let amber50 = "text-amber-50"
        let amber100 = "text-amber-100"
        let amber200 = "text-amber-200"
        let amber300 = "text-amber-300"
        let amber400 = "text-amber-400"
        let amber500 = "text-amber-500"
        let amber600 = "text-amber-600"
        let amber700 = "text-amber-700"
        let amber800 = "text-amber-800"
        let amber900 = "text-amber-900"
        let amber950 = "text-amber-950"
        let yellow50 = "text-yellow-50"
        let yellow100 = "text-yellow-100"
        let yellow200 = "text-yellow-200"
        let yellow300 = "text-yellow-300"
        let yellow400 = "text-yellow-400"
        let yellow500 = "text-yellow-500"
        let yellow600 = "text-yellow-600"
        let yellow700 = "text-yellow-700"
        let yellow800 = "text-yellow-800"
        let yellow900 = "text-yellow-900"
        let yellow950 = "text-yellow-950"
        let lime50 = "text-lime-50"
        let lime100 = "text-lime-100"
        let lime200 = "text-lime-200"
        let lime300 = "text-lime-300"
        let lime400 = "text-lime-400"
        let lime500 = "text-lime-500"
        let lime600 = "text-lime-600"
        let lime700 = "text-lime-700"
        let lime800 = "text-lime-800"
        let lime900 = "text-lime-900"
        let lime950 = "text-lime-950"
        let green50 = "text-green-50"
        let green100 = "text-green-100"
        let green200 = "text-green-200"
        let green300 = "text-green-300"
        let green400 = "text-green-400"
        let green500 = "text-green-500"
        let green600 = "text-green-600"
        let green700 = "text-green-700"
        let green800 = "text-green-800"
        let green900 = "text-green-900"
        let green950 = "text-green-950"
        let emerald50 = "text-emerald-50"
        let emerald100 = "text-emerald-100"
        let emerald200 = "text-emerald-200"
        let emerald300 = "text-emerald-300"
        let emerald400 = "text-emerald-400"
        let emerald500 = "text-emerald-500"
        let emerald600 = "text-emerald-600"
        let emerald700 = "text-emerald-700"
        let emerald800 = "text-emerald-800"
        let emerald900 = "text-emerald-900"
        let emerald950 = "text-emerald-950"
        let teal50 = "text-teal-50"
        let teal100 = "text-teal-100"
        let teal200 = "text-teal-200"
        let teal300 = "text-teal-300"
        let teal400 = "text-teal-400"
        let teal500 = "text-teal-500"
        let teal600 = "text-teal-600"
        let teal700 = "text-teal-700"
        let teal800 = "text-teal-800"
        let teal900 = "text-teal-900"
        let teal950 = "text-teal-950"
        let cyan50 = "text-cyan-50"
        let cyan100 = "text-cyan-100"
        let cyan200 = "text-cyan-200"
        let cyan300 = "text-cyan-300"
        let cyan400 = "text-cyan-400"
        let cyan500 = "text-cyan-500"
        let cyan600 = "text-cyan-600"
        let cyan700 = "text-cyan-700"
        let cyan800 = "text-cyan-800"
        let cyan900 = "text-cyan-900"
        let cyan950 = "text-cyan-950"
        let sky50 = "text-sky-50"
        let sky100 = "text-sky-100"
        let sky200 = "text-sky-200"
        let sky300 = "text-sky-300"
        let sky400 = "text-sky-400"
        let sky500 = "text-sky-500"
        let sky600 = "text-sky-600"
        let sky700 = "text-sky-700"
        let sky800 = "text-sky-800"
        let sky900 = "text-sky-900"
        let sky950 = "text-sky-950"
        let blue50 = "text-blue-50"
        let blue100 = "text-blue-100"
        let blue200 = "text-blue-200"
        let blue300 = "text-blue-300"
        let blue400 = "text-blue-400"
        let blue500 = "text-blue-500"
        let blue600 = "text-blue-600"
        let blue700 = "text-blue-700"
        let blue800 = "text-blue-800"
        let blue900 = "text-blue-900"
        let blue950 = "text-blue-950"
        let indigo50 = "text-indigo-50"
        let indigo100 = "text-indigo-100"
        let indigo200 = "text-indigo-200"
        let indigo300 = "text-indigo-300"
        let indigo400 = "text-indigo-400"
        let indigo500 = "text-indigo-500"
        let indigo600 = "text-indigo-600"
        let indigo700 = "text-indigo-700"
        let indigo800 = "text-indigo-800"
        let indigo900 = "text-indigo-900"
        let indigo950 = "text-indigo-950"
        let violet50 = "text-violet-50"
        let violet100 = "text-violet-100"
        let violet200 = "text-violet-200"
        let violet300 = "text-violet-300"
        let violet400 = "text-violet-400"
        let violet500 = "text-violet-500"
        let violet600 = "text-violet-600"
        let violet700 = "text-violet-700"
        let violet800 = "text-violet-800"
        let violet900 = "text-violet-900"
        let violet950 = "text-violet-950"
        let purple50 = "text-purple-50"
        let purple100 = "text-purple-100"
        let purple200 = "text-purple-200"
        let purple300 = "text-purple-300"
        let purple400 = "text-purple-400"
        let purple500 = "text-purple-500"
        let purple600 = "text-purple-600"
        let purple700 = "text-purple-700"
        let purple800 = "text-purple-800"
        let purple900 = "text-purple-900"
        let purple950 = "text-purple-950"
        let fuchsia50 = "text-fuchsia-50"
        let fuchsia100 = "text-fuchsia-100"
        let fuchsia200 = "text-fuchsia-200"
        let fuchsia300 = "text-fuchsia-300"
        let fuchsia400 = "text-fuchsia-400"
        let fuchsia500 = "text-fuchsia-500"
        let fuchsia600 = "text-fuchsia-600"
        let fuchsia700 = "text-fuchsia-700"
        let fuchsia800 = "text-fuchsia-800"
        let fuchsia900 = "text-fuchsia-900"
        let fuchsia950 = "text-fuchsia-950"
        let pink50 = "text-pink-50"
        let pink100 = "text-pink-100"
        let pink200 = "text-pink-200"
        let pink300 = "text-pink-300"
        let pink400 = "text-pink-400"
        let pink500 = "text-pink-500"
        let pink600 = "text-pink-600"
        let pink700 = "text-pink-700"
        let pink800 = "text-pink-800"
        let pink900 = "text-pink-900"
        let pink950 = "text-pink-950"
        let rose50 = "text-rose-50"
        let rose100 = "text-rose-100"
        let rose200 = "text-rose-200"
        let rose300 = "text-rose-300"
        let rose400 = "text-rose-400"
        let rose500 = "text-rose-500"
        let rose600 = "text-rose-600"
        let rose700 = "text-rose-700"
        let rose800 = "text-rose-800"
        let rose900 = "text-rose-900"
        let rose950 = "text-rose-950"

    /// padding utilities
    module padding =
        let p0 = "p-0"
        let p1 = "p-1"
        let p2 = "p-2"
        let p3 = "p-3"
        let p4 = "p-4"
        let p5 = "p-5"
        let p6 = "p-6"
        let p7 = "p-7"
        let p8 = "p-8"
        let p9 = "p-9"
        let p10 = "p-10"
        let p11 = "p-11"
        let p12 = "p-12"
        let p14 = "p-14"
        let p16 = "p-16"
        let p20 = "p-20"
        let p24 = "p-24"
        let pt0 = "pt-0"
        let pt1 = "pt-1"
        let pt2 = "pt-2"
        let pt3 = "pt-3"
        let pt4 = "pt-4"
        let pt5 = "pt-5"
        let pt6 = "pt-6"
        let pt8 = "pt-8"
        let pb0 = "pb-0"
        let pb1 = "pb-1"
        let pb2 = "pb-2"
        let pb3 = "pb-3"
        let pb4 = "pb-4"
        let pb5 = "pb-5"
        let pb6 = "pb-6"
        let pb8 = "pb-8"
        let pr0 = "pr-0"
        let pr1 = "pr-1"
        let pr2 = "pr-2"
        let pr3 = "pr-3"
        let pr4 = "pr-4"
        let pr5 = "pr-5"
        let pr6 = "pr-6"
        let pr8 = "pr-8"
        let pl0 = "pl-0"
        let pl1 = "pl-1"
        let pl2 = "pl-2"
        let pl3 = "pl-3"
        let pl4 = "pl-4"
        let pl5 = "pl-5"
        let pl6 = "pl-6"
        let pl8 = "pl-8"
        let px0 = "px-0"
        let px1 = "px-1"
        let px2 = "px-2"
        let px3 = "px-3"
        let px4 = "px-4"
        let px5 = "px-5"
        let px6 = "px-6"
        let px8 = "px-8"
        let py0 = "py-0"
        let py1 = "py-1"
        let py2 = "py-2"
        let py3 = "py-3"
        let py4 = "py-4"
        let py5 = "py-5"
        let py6 = "py-6"
        let py8 = "py-8"

    /// position utilities
    module position =
        let absolute = "absolute"
        let relative = "relative"
        let sticky = "sticky"
        let ``fixed'`` = "fixed"
        let ``static'`` = "static"
        let inset0 = "inset-0"
        let insetAuto = "inset-auto"
        let insetX0 = "inset-x-0"
        let insetXAuto = "inset-x-auto"
        let insetY0 = "inset-y-0"
        let insetYAuto = "inset-y-auto"
        let top0 = "top-0"
        let top1 = "top-1"
        let top2 = "top-2"
        let top3 = "top-3"
        let top4 = "top-4"
        let topAuto = "top-auto"
        let topFull = "top-full"
        let right0 = "right-0"
        let right1 = "right-1"
        let right2 = "right-2"
        let right3 = "right-3"
        let right4 = "right-4"
        let rightAuto = "right-auto"
        let rightFull = "right-full"
        let bottom0 = "bottom-0"
        let bottom1 = "bottom-1"
        let bottom2 = "bottom-2"
        let bottom3 = "bottom-3"
        let bottom4 = "bottom-4"
        let bottomAuto = "bottom-auto"
        let bottomFull = "bottom-full"
        let left0 = "left-0"
        let left1 = "left-1"
        let left2 = "left-2"
        let left3 = "left-3"
        let left4 = "left-4"
        let leftAuto = "left-auto"
        let leftFull = "left-full"

    /// visibility utilities
    module visibility =
        let visible = "visible"
        let invisible = "invisible"

    /// width utilities
    module width =
        let w0 = "w-0"
        let w1 = "w-1"
        let w2 = "w-2"
        let w3 = "w-3"
        let w4 = "w-4"
        let w5 = "w-5"
        let w6 = "w-6"
        let w7 = "w-7"
        let w8 = "w-8"
        let w9 = "w-9"
        let w10 = "w-10"
        let w11 = "w-11"
        let w12 = "w-12"
        let w14 = "w-14"
        let w16 = "w-16"
        let w20 = "w-20"
        let w24 = "w-24"
        let w28 = "w-28"
        let w32 = "w-32"
        let w36 = "w-36"
        let w40 = "w-40"
        let w44 = "w-44"
        let w48 = "w-48"
        let w52 = "w-52"
        let w56 = "w-56"
        let w60 = "w-60"
        let w64 = "w-64"
        let w72 = "w-72"
        let w80 = "w-80"
        let w92 = "w-92"
        let w96 = "w-96"
        let wAuto = "w-auto"
        let ``w1/2`` = "w-1/2"
        let ``w1/3`` = "w-1/3"
        let ``w2/3`` = "w-2/3"
        let ``w1/4`` = "w-1/4"
        let ``w2/4`` = "w-2/4"
        let ``w3/4`` = "w-3/4"
        let ``w1/5`` = "w-1/5"
        let ``w2/5`` = "w-2/5"
        let ``w3/5`` = "w-3/5"
        let ``w4/5`` = "w-4/5"
        let ``w1/6`` = "w-1/6"
        let ``w2/6`` = "w-2/6"
        let ``w3/6`` = "w-3/6"
        let ``w4/6`` = "w-4/6"
        let ``w5/6`` = "w-5/6"
        let ``w1/12`` = "w-1/12"
        let ``w2/12`` = "w-2/12"
        let ``w3/12`` = "w-3/12"
        let ``w4/12`` = "w-4/12"
        let ``w5/12`` = "w-5/12"
        let ``w6/12`` = "w-6/12"
        let ``w7/12`` = "w-7/12"
        let ``w8/12`` = "w-8/12"
        let ``w9/12`` = "w-9/12"
        let ``w10/12`` = "w-10/12"
        let ``w11/12`` = "w-11/12"
        let wFull = "w-full"
        let wScreen = "w-screen"
        let wMin = "w-min"
        let wMax = "w-max"
        let wFit = "w-fit"

    /// grid utilities
    module grid =
        let ``cols-none`` = "grid-cols-none"
        let ``cols-1`` = "grid-cols-1"
        let ``cols-2`` = "grid-cols-2"
        let ``cols-3`` = "grid-cols-3"
        let ``cols-4`` = "grid-cols-4"
        let ``cols-5`` = "grid-cols-5"
        let ``cols-6`` = "grid-cols-6"
        let ``cols-7`` = "grid-cols-7"
        let ``cols-8`` = "grid-cols-8"
        let ``cols-9`` = "grid-cols-9"
        let ``cols-10`` = "grid-cols-10"
        let ``cols-11`` = "grid-cols-11"
        let ``cols-12`` = "grid-cols-12"
        let grid = "grid"
        let ``col-span-1`` = "col-span-1"
        let ``col-span-2`` = "col-span-2"
        let ``col-span-3`` = "col-span-3"
        let ``col-span-4`` = "col-span-4"
        let ``col-span-5`` = "col-span-5"
        let ``col-span-6`` = "col-span-6"
        let ``col-span-7`` = "col-span-7"
        let ``col-span-8`` = "col-span-8"
        let ``col-span-9`` = "col-span-9"
        let ``col-span-10`` = "col-span-10"
        let ``col-span-11`` = "col-span-11"
        let ``col-span-12`` = "col-span-12"
        let ``col-span-full`` = "col-span-full"
        let ``row-span-1`` = "row-span-1"
        let ``row-span-2`` = "row-span-2"
        let ``row-span-3`` = "row-span-3"
        let ``row-span-4`` = "row-span-4"
        let ``row-span-5`` = "row-span-5"
        let ``row-span-6`` = "row-span-6"
        let ``row-span-full`` = "row-span-full"

    /// gap utilities
    module gap =
        let ``gap-0`` = "gap-0"
        let ``gap-1`` = "gap-1"
        let ``gap-2`` = "gap-2"
        let ``gap-3`` = "gap-3"
        let ``gap-4`` = "gap-4"
        let ``gap-5`` = "gap-5"
        let ``gap-6`` = "gap-6"
        let ``gap-7`` = "gap-7"
        let ``gap-x-0`` = "gap-x-0"
        let ``gap-y-0`` = "gap-y-0"

    /// textAlign utilities
    module textAlign =
        let left = "text-left"
        let center = "text-center"
        let right = "text-right"
        let justify = "text-justify"
        let start = "text-start"
        let ``end`` = "text-end"

    /// alignItems utilities
    module alignItems =
        let itemsStart = "items-start"
        let itemsEnd = "items-end"
        let itemsEndSafe = "items-end-safe"
        let itemsCenter = "items-center"
        let itemsCenterSafe = "items-center-safe"
        let itemsBaseline = "items-baseline"
        let itemsBaselineLast = "items-baseline-last"
        let itemsStretch = "items-stretch"

    /// zIndex utilities
    module zIndex =
        let z0 = "z-0"
        let z10 = "z-10"
        let z20 = "z-20"
        let z30 = "z-30"
        let z40 = "z-40"
        let z50 = "z-50"
        let zAuto = "z-auto"

    /// opacity utilities
    module opacity =
        let opacity0 = "opacity-0"
        let opacity5 = "opacity-5"
        let opacity10 = "opacity-10"
        let opacity15 = "opacity-15"
        let opacity20 = "opacity-20"
        let opacity25 = "opacity-25"
        let opacity30 = "opacity-30"
        let opacity35 = "opacity-35"
        let opacity40 = "opacity-40"
        let opacity45 = "opacity-45"
        let opacity50 = "opacity-50"
        let opacity55 = "opacity-55"
        let opacity60 = "opacity-60"
        let opacity65 = "opacity-65"
        let opacity70 = "opacity-70"
        let opacity75 = "opacity-75"
        let opacity80 = "opacity-80"
        let opacity85 = "opacity-85"
        let opacity90 = "opacity-90"
        let opacity95 = "opacity-95"
        let opacity100 = "opacity-100"

    /// bgOpacity utilities
    module bgOpacity =
        let bgOpacity0 = "bg-opacity-0"
        let bgOpacity5 = "bg-opacity-5"
        let bgOpacity10 = "bg-opacity-10"
        let bgOpacity20 = "bg-opacity-20"
        let bgOpacity25 = "bg-opacity-25"
        let bgOpacity30 = "bg-opacity-30"
        let bgOpacity40 = "bg-opacity-40"
        let bgOpacity50 = "bg-opacity-50"
        let bgOpacity60 = "bg-opacity-60"
        let bgOpacity70 = "bg-opacity-70"
        let bgOpacity75 = "bg-opacity-75"
        let bgOpacity80 = "bg-opacity-80"
        let bgOpacity90 = "bg-opacity-90"
        let bgOpacity95 = "bg-opacity-95"
        let bgOpacity100 = "bg-opacity-100"

    /// lineHeight utilities
    module lineHeight =
        let leadingNone = "leading-none"
        let leadingTight = "leading-tight"
        let leadingSnug = "leading-snug"
        let leadingNormal = "leading-normal"
        let leadingRelaxed = "leading-relaxed"
        let leadingLoose = "leading-loose"
        let leading3 = "leading-3"
        let leading4 = "leading-4"
        let leading5 = "leading-5"
        let leading6 = "leading-6"
        let leading7 = "leading-7"
        let leading8 = "leading-8"
        let leading9 = "leading-9"
        let leading10 = "leading-10"

    /// letterSpacing utilities
    module letterSpacing =
        let trackingTighter = "tracking-tighter"
        let trackingTight = "tracking-tight"
        let trackingNormal = "tracking-normal"
        let trackingWide = "tracking-wide"
        let trackingWider = "tracking-wider"
        let trackingWidest = "tracking-widest"

    /// textDecoration utilities
    module textDecoration =
        let underline = "underline"
        let overline = "overline"
        let lineThrough = "line-through"
        let noUnderline = "no-underline"

    /// textDecorationStyle utilities
    module textDecorationStyle =
        let decorationSolid = "decoration-solid"
        let decorationDouble = "decoration-double"
        let decorationDotted = "decoration-dotted"
        let decorationDashed = "decoration-dashed"
        let decorationWavy = "decoration-wavy"

    /// textDecorationThickness utilities
    module textDecorationThickness =
        let decorationAuto = "decoration-auto"
        let decorationFromFont = "decoration-from-font"
        let decoration0 = "decoration-0"
        let decoration1 = "decoration-1"
        let decoration2 = "decoration-2"
        let decoration4 = "decoration-4"
        let decoration8 = "decoration-8"

    /// textUnderlineOffset utilities
    module textUnderlineOffset =
        let underlineOffsetAuto = "underline-offset-auto"
        let underlineOffset0 = "underline-offset-0"
        let underlineOffset1 = "underline-offset-1"
        let underlineOffset2 = "underline-offset-2"
        let underlineOffset4 = "underline-offset-4"
        let underlineOffset8 = "underline-offset-8"

    /// textTransform utilities
    module textTransform =
        let uppercase = "uppercase"
        let lowercase = "lowercase"
        let capitalize = "capitalize"
        let normalCase = "normal-case"

    /// textOverflow utilities
    module textOverflow =
        let truncate = "truncate"
        let textEllipsis = "text-ellipsis"
        let textClip = "text-clip"

    /// textWrap utilities
    module textWrap =
        let textWrap = "text-wrap"
        let textNowrap = "text-nowrap"
        let textBalance = "text-balance"
        let textPretty = "text-pretty"

    /// whitespace utilities
    module whitespace =
        let whitespaceNormal = "whitespace-normal"
        let whitespaceNowrap = "whitespace-nowrap"
        let whitespacePre = "whitespace-pre"
        let whitespacePreLine = "whitespace-pre-line"
        let whitespacePreWrap = "whitespace-pre-wrap"
        let whitespaceBreakSpaces = "whitespace-break-spaces"

    /// wordBreak utilities
    module wordBreak =
        let breakNormal = "break-normal"
        let breakWords = "break-words"
        let breakAll = "break-all"
        let breakKeep = "break-keep"

    /// hyphens utilities
    module hyphens =
        let hyphensNone = "hyphens-none"
        let hyphensManual = "hyphens-manual"
        let hyphensAuto = "hyphens-auto"

    /// fontFamily utilities
    module fontFamily =
        let fontSans = "font-sans"
        let fontSerif = "font-serif"
        let fontMono = "font-mono"

    /// fontStyle utilities
    module fontStyle =
        let italic = "italic"
        let notItalic = "not-italic"

    /// fontVariantNumeric utilities
    module fontVariantNumeric =
        let normalNums = "normal-nums"
        let ordinal = "ordinal"
        let slashedZero = "slashed-zero"
        let liningNums = "lining-nums"
        let oldstyleNums = "oldstyle-nums"
        let proportionalNums = "proportional-nums"
        let tabularNums = "tabular-nums"
        let diagonalFractions = "diagonal-fractions"
        let stackedFractions = "stacked-fractions"

    /// listStyleType utilities
    module listStyleType =
        let listNone = "list-none"
        let listDisc = "list-disc"
        let listDecimal = "list-decimal"

    /// listStylePosition utilities
    module listStylePosition =
        let listInside = "list-inside"
        let listOutside = "list-outside"

    /// textIndent utilities
    module textIndent =
        let indent0 = "indent-0"
        let indent1 = "indent-1"
        let indent2 = "indent-2"
        let indent4 = "indent-4"
        let indent6 = "indent-6"
        let indent8 = "indent-8"
        let indent10 = "indent-10"
        let indent12 = "indent-12"
        let indent16 = "indent-16"
        let indent20 = "indent-20"
        let indent24 = "indent-24"

    /// verticalAlign utilities
    module verticalAlign =
        let alignBaseline = "align-baseline"
        let alignTop = "align-top"
        let alignMiddle = "align-middle"
        let alignBottom = "align-bottom"
        let alignTextTop = "align-text-top"
        let alignTextBottom = "align-text-bottom"
        let alignSub = "align-sub"
        let alignSuper = "align-super"

    /// minWidth utilities
    module minWidth =
        let minW0 = "min-w-0"
        let minW1 = "min-w-1"
        let minW2 = "min-w-2"
        let minW3 = "min-w-3"
        let minW4 = "min-w-4"
        let minW5 = "min-w-5"
        let minW6 = "min-w-6"
        let minW8 = "min-w-8"
        let minW10 = "min-w-10"
        let minW12 = "min-w-12"
        let minW16 = "min-w-16"
        let minW20 = "min-w-20"
        let minW24 = "min-w-24"
        let minW32 = "min-w-32"
        let minW40 = "min-w-40"
        let minW48 = "min-w-48"
        let minW56 = "min-w-56"
        let minW64 = "min-w-64"
        let minW72 = "min-w-72"
        let minW80 = "min-w-80"
        let minW96 = "min-w-96"
        let minWFull = "min-w-full"
        let minWMin = "min-w-min"
        let minWMax = "min-w-max"
        let minWFit = "min-w-fit"

    /// aspectRatio utilities
    module aspectRatio =
        let aspectAuto = "aspect-auto"
        let aspectSquare = "aspect-square"
        let aspectVideo = "aspect-video"

    /// size utilities
    module size =
        let size0 = "size-0"
        let size1 = "size-1"
        let size2 = "size-2"
        let size3 = "size-3"
        let size4 = "size-4"
        let size5 = "size-5"
        let size6 = "size-6"
        let size7 = "size-7"
        let size8 = "size-8"
        let size9 = "size-9"
        let size10 = "size-10"
        let size11 = "size-11"
        let size12 = "size-12"
        let size14 = "size-14"
        let size16 = "size-16"
        let size20 = "size-20"
        let size24 = "size-24"
        let size28 = "size-28"
        let size32 = "size-32"
        let size36 = "size-36"
        let size40 = "size-40"
        let size44 = "size-44"
        let size48 = "size-48"
        let size52 = "size-52"
        let size56 = "size-56"
        let size60 = "size-60"
        let size64 = "size-64"
        let size72 = "size-72"
        let size80 = "size-80"
        let size96 = "size-96"
        let sizeAuto = "size-auto"
        let sizeFull = "size-full"
        let sizeMin = "size-min"
        let sizeMax = "size-max"
        let sizeFit = "size-fit"

    /// borderStyle utilities
    module borderStyle =
        let borderSolid = "border-solid"
        let borderDashed = "border-dashed"
        let borderDotted = "border-dotted"
        let borderDouble = "border-double"
        let borderHidden = "border-hidden"
        let borderNone = "border-none"

    /// border utilities
    module border =
        let border = "border"
        let border0 = "border-0"
        let border2 = "border-2"
        let border4 = "border-4"
        let border8 = "border-8"
        let borderX = "border-x"
        let borderX0 = "border-x-0"
        let borderX2 = "border-x-2"
        let borderX4 = "border-x-4"
        let borderX8 = "border-x-8"
        let borderY = "border-y"
        let borderY0 = "border-y-0"
        let borderY2 = "border-y-2"
        let borderY4 = "border-y-4"
        let borderY8 = "border-y-8"
        let borderT = "border-t"
        let borderT0 = "border-t-0"
        let borderT2 = "border-t-2"
        let borderT4 = "border-t-4"
        let borderT8 = "border-t-8"
        let borderR = "border-r"
        let borderR0 = "border-r-0"
        let borderR2 = "border-r-2"
        let borderR4 = "border-r-4"
        let borderR8 = "border-r-8"
        let borderB = "border-b"
        let borderB0 = "border-b-0"
        let borderB2 = "border-b-2"
        let borderB4 = "border-b-4"
        let borderB8 = "border-b-8"
        let borderL = "border-l"
        let borderL0 = "border-l-0"
        let borderL2 = "border-l-2"
        let borderL4 = "border-l-4"
        let borderL8 = "border-l-8"

    /// borderColor utilities
    module borderColor =
        let borderInherit = "border-inherit"
        let borderCurrent = "border-current"
        let borderTransparent = "border-transparent"
        let borderBlack = "border-black"
        let borderWhite = "border-white"
        let borderSlate50 = "border-slate-50"
        let borderSlate100 = "border-slate-100"
        let borderSlate200 = "border-slate-200"
        let borderSlate300 = "border-slate-300"
        let borderSlate400 = "border-slate-400"
        let borderSlate500 = "border-slate-500"
        let borderSlate600 = "border-slate-600"
        let borderSlate700 = "border-slate-700"
        let borderSlate800 = "border-slate-800"
        let borderSlate900 = "border-slate-900"
        let borderSlate950 = "border-slate-950"
        let borderGray50 = "border-gray-50"
        let borderGray100 = "border-gray-100"
        let borderGray200 = "border-gray-200"
        let borderGray300 = "border-gray-300"
        let borderGray400 = "border-gray-400"
        let borderGray500 = "border-gray-500"
        let borderGray600 = "border-gray-600"
        let borderGray700 = "border-gray-700"
        let borderGray800 = "border-gray-800"
        let borderGray900 = "border-gray-900"
        let borderGray950 = "border-gray-950"
        let borderZinc50 = "border-zinc-50"
        let borderZinc100 = "border-zinc-100"
        let borderZinc200 = "border-zinc-200"
        let borderZinc300 = "border-zinc-300"
        let borderZinc400 = "border-zinc-400"
        let borderZinc500 = "border-zinc-500"
        let borderZinc600 = "border-zinc-600"
        let borderZinc700 = "border-zinc-700"
        let borderZinc800 = "border-zinc-800"
        let borderZinc900 = "border-zinc-900"
        let borderZinc950 = "border-zinc-950"
        let borderRed50 = "border-red-50"
        let borderRed100 = "border-red-100"
        let borderRed200 = "border-red-200"
        let borderRed300 = "border-red-300"
        let borderRed400 = "border-red-400"
        let borderRed500 = "border-red-500"
        let borderRed600 = "border-red-600"
        let borderRed700 = "border-red-700"
        let borderRed800 = "border-red-800"
        let borderRed900 = "border-red-900"
        let borderRed950 = "border-red-950"
        let borderOrange50 = "border-orange-50"
        let borderOrange100 = "border-orange-100"
        let borderOrange200 = "border-orange-200"
        let borderOrange300 = "border-orange-300"
        let borderOrange400 = "border-orange-400"
        let borderOrange500 = "border-orange-500"
        let borderOrange600 = "border-orange-600"
        let borderOrange700 = "border-orange-700"
        let borderOrange800 = "border-orange-800"
        let borderOrange900 = "border-orange-900"
        let borderOrange950 = "border-orange-950"
        let borderYellow50 = "border-yellow-50"
        let borderYellow100 = "border-yellow-100"
        let borderYellow200 = "border-yellow-200"
        let borderYellow300 = "border-yellow-300"
        let borderYellow400 = "border-yellow-400"
        let borderYellow500 = "border-yellow-500"
        let borderYellow600 = "border-yellow-600"
        let borderYellow700 = "border-yellow-700"
        let borderYellow800 = "border-yellow-800"
        let borderYellow900 = "border-yellow-900"
        let borderYellow950 = "border-yellow-950"
        let borderGreen50 = "border-green-50"
        let borderGreen100 = "border-green-100"
        let borderGreen200 = "border-green-200"
        let borderGreen300 = "border-green-300"
        let borderGreen400 = "border-green-400"
        let borderGreen500 = "border-green-500"
        let borderGreen600 = "border-green-600"
        let borderGreen700 = "border-green-700"
        let borderGreen800 = "border-green-800"
        let borderGreen900 = "border-green-900"
        let borderGreen950 = "border-green-950"
        let borderBlue50 = "border-blue-50"
        let borderBlue100 = "border-blue-100"
        let borderBlue200 = "border-blue-200"
        let borderBlue300 = "border-blue-300"
        let borderBlue400 = "border-blue-400"
        let borderBlue500 = "border-blue-500"
        let borderBlue600 = "border-blue-600"
        let borderBlue700 = "border-blue-700"
        let borderBlue800 = "border-blue-800"
        let borderBlue900 = "border-blue-900"
        let borderBlue950 = "border-blue-950"
        let borderIndigo50 = "border-indigo-50"
        let borderIndigo100 = "border-indigo-100"
        let borderIndigo200 = "border-indigo-200"
        let borderIndigo300 = "border-indigo-300"
        let borderIndigo400 = "border-indigo-400"
        let borderIndigo500 = "border-indigo-500"
        let borderIndigo600 = "border-indigo-600"
        let borderIndigo700 = "border-indigo-700"
        let borderIndigo800 = "border-indigo-800"
        let borderIndigo900 = "border-indigo-900"
        let borderIndigo950 = "border-indigo-950"
        let borderPurple50 = "border-purple-50"
        let borderPurple100 = "border-purple-100"
        let borderPurple200 = "border-purple-200"
        let borderPurple300 = "border-purple-300"
        let borderPurple400 = "border-purple-400"
        let borderPurple500 = "border-purple-500"
        let borderPurple600 = "border-purple-600"
        let borderPurple700 = "border-purple-700"
        let borderPurple800 = "border-purple-800"
        let borderPurple900 = "border-purple-900"
        let borderPurple950 = "border-purple-950"
        let borderPink50 = "border-pink-50"
        let borderPink100 = "border-pink-100"
        let borderPink200 = "border-pink-200"
        let borderPink300 = "border-pink-300"
        let borderPink400 = "border-pink-400"
        let borderPink500 = "border-pink-500"
        let borderPink600 = "border-pink-600"
        let borderPink700 = "border-pink-700"
        let borderPink800 = "border-pink-800"
        let borderPink900 = "border-pink-900"
        let borderPink950 = "border-pink-950"

    /// divide utilities
    module divide =
        let divideX = "divide-x"
        let divideX0 = "divide-x-0"
        let divideX2 = "divide-x-2"
        let divideX4 = "divide-x-4"
        let divideX8 = "divide-x-8"
        let divideY = "divide-y"
        let divideY0 = "divide-y-0"
        let divideY2 = "divide-y-2"
        let divideY4 = "divide-y-4"
        let divideY8 = "divide-y-8"
        let divideXReverse = "divide-x-reverse"
        let divideYReverse = "divide-y-reverse"
        let divideSolid = "divide-solid"
        let divideDashed = "divide-dashed"
        let divideDotted = "divide-dotted"
        let divideDouble = "divide-double"
        let divideNone = "divide-none"

    /// ring utilities
    module ring =
        let ring = "ring"
        let ring0 = "ring-0"
        let ring1 = "ring-1"
        let ring2 = "ring-2"
        let ring4 = "ring-4"
        let ring8 = "ring-8"
        let ringInset = "ring-inset"

    /// ringColor utilities
    module ringColor =
        let ringInherit = "ring-inherit"
        let ringCurrent = "ring-current"
        let ringTransparent = "ring-transparent"
        let ringBlack = "ring-black"
        let ringWhite = "ring-white"
        let ringSlate50 = "ring-slate-50"
        let ringSlate100 = "ring-slate-100"
        let ringSlate200 = "ring-slate-200"
        let ringSlate300 = "ring-slate-300"
        let ringSlate400 = "ring-slate-400"
        let ringSlate500 = "ring-slate-500"
        let ringSlate600 = "ring-slate-600"
        let ringSlate700 = "ring-slate-700"
        let ringSlate800 = "ring-slate-800"
        let ringSlate900 = "ring-slate-900"
        let ringGray50 = "ring-gray-50"
        let ringGray100 = "ring-gray-100"
        let ringGray200 = "ring-gray-200"
        let ringGray300 = "ring-gray-300"
        let ringGray400 = "ring-gray-400"
        let ringGray500 = "ring-gray-500"
        let ringGray600 = "ring-gray-600"
        let ringGray700 = "ring-gray-700"
        let ringGray800 = "ring-gray-800"
        let ringGray900 = "ring-gray-900"
        let ringBlue50 = "ring-blue-50"
        let ringBlue100 = "ring-blue-100"
        let ringBlue200 = "ring-blue-200"
        let ringBlue300 = "ring-blue-300"
        let ringBlue400 = "ring-blue-400"
        let ringBlue500 = "ring-blue-500"
        let ringBlue600 = "ring-blue-600"
        let ringBlue700 = "ring-blue-700"
        let ringBlue800 = "ring-blue-800"
        let ringBlue900 = "ring-blue-900"
        let ringRed50 = "ring-red-50"
        let ringRed100 = "ring-red-100"
        let ringRed200 = "ring-red-200"
        let ringRed300 = "ring-red-300"
        let ringRed400 = "ring-red-400"
        let ringRed500 = "ring-red-500"
        let ringRed600 = "ring-red-600"
        let ringRed700 = "ring-red-700"
        let ringRed800 = "ring-red-800"
        let ringRed900 = "ring-red-900"
        let ringGreen50 = "ring-green-50"
        let ringGreen100 = "ring-green-100"
        let ringGreen200 = "ring-green-200"
        let ringGreen300 = "ring-green-300"
        let ringGreen400 = "ring-green-400"
        let ringGreen500 = "ring-green-500"
        let ringGreen600 = "ring-green-600"
        let ringGreen700 = "ring-green-700"
        let ringGreen800 = "ring-green-800"
        let ringGreen900 = "ring-green-900"

    /// ringOffsetWidth utilities
    module ringOffsetWidth =
        let ringOffset0 = "ring-offset-0"
        let ringOffset1 = "ring-offset-1"
        let ringOffset2 = "ring-offset-2"
        let ringOffset4 = "ring-offset-4"
        let ringOffset8 = "ring-offset-8"

    /// outlineWidth utilities
    module outlineWidth =
        let outlineWidth0 = "outline-0"
        let outlineWidth1 = "outline-1"
        let outlineWidth2 = "outline-2"
        let outlineWidth4 = "outline-4"
        let outlineWidth8 = "outline-8"

    /// outlineOffset utilities
    module outlineOffset =
        let outlineOffset0 = "outline-offset-0"
        let outlineOffset1 = "outline-offset-1"
        let outlineOffset2 = "outline-offset-2"
        let outlineOffset4 = "outline-offset-4"
        let outlineOffset8 = "outline-offset-8"

    /// scale utilities
    module scale =
        let scale0 = "scale-0"
        let scale50 = "scale-50"
        let scale75 = "scale-75"
        let scale90 = "scale-90"
        let scale95 = "scale-95"
        let scale100 = "scale-100"
        let scale105 = "scale-105"
        let scale110 = "scale-110"
        let scale125 = "scale-125"
        let scale150 = "scale-150"
        let scaleX0 = "scale-x-0"
        let scaleX50 = "scale-x-50"
        let scaleX75 = "scale-x-75"
        let scaleX90 = "scale-x-90"
        let scaleX95 = "scale-x-95"
        let scaleX100 = "scale-x-100"
        let scaleX105 = "scale-x-105"
        let scaleX110 = "scale-x-110"
        let scaleX125 = "scale-x-125"
        let scaleX150 = "scale-x-150"
        let scaleY0 = "scale-y-0"
        let scaleY50 = "scale-y-50"
        let scaleY75 = "scale-y-75"
        let scaleY90 = "scale-y-90"
        let scaleY95 = "scale-y-95"
        let scaleY100 = "scale-y-100"
        let scaleY105 = "scale-y-105"
        let scaleY110 = "scale-y-110"
        let scaleY125 = "scale-y-125"
        let scaleY150 = "scale-y-150"

    /// rotate utilities
    module rotate =
        let rotate0 = "rotate-0"
        let rotate1 = "rotate-1"
        let rotate2 = "rotate-2"
        let rotate3 = "rotate-3"
        let rotate6 = "rotate-6"
        let rotate12 = "rotate-12"
        let rotate45 = "rotate-45"
        let rotate90 = "rotate-90"
        let rotate180 = "rotate-180"
        let ``-rotate1`` = "-rotate-1"
        let ``-rotate2`` = "-rotate-2"
        let ``-rotate3`` = "-rotate-3"
        let ``-rotate6`` = "-rotate-6"
        let ``-rotate12`` = "-rotate-12"
        let ``-rotate45`` = "-rotate-45"
        let ``-rotate90`` = "-rotate-90"
        let ``-rotate180`` = "-rotate-180"

    /// translate utilities
    module translate =
        let translateX0 = "translate-x-0"
        let translateX1 = "translate-x-1"
        let translateX2 = "translate-x-2"
        let translateX3 = "translate-x-3"
        let translateX4 = "translate-x-4"
        let translateX5 = "translate-x-5"
        let translateX6 = "translate-x-6"
        let translateX8 = "translate-x-8"
        let translateX10 = "translate-x-10"
        let translateX12 = "translate-x-12"
        let translateX16 = "translate-x-16"
        let translateX20 = "translate-x-20"
        let translateX24 = "translate-x-24"
        let translateX32 = "translate-x-32"
        let translateX40 = "translate-x-40"
        let translateX48 = "translate-x-48"
        let translateX56 = "translate-x-56"
        let translateX64 = "translate-x-64"
        let ``translateX1/2`` = "translate-x-1/2"
        let ``translateX1/3`` = "translate-x-1/3"
        let ``translateX2/3`` = "translate-x-2/3"
        let ``translateX1/4`` = "translate-x-1/4"
        let ``translateX3/4`` = "translate-x-3/4"
        let translateXFull = "translate-x-full"
        let ``-translateX1`` = "-translate-x-1"
        let ``-translateX2`` = "-translate-x-2"
        let ``-translateX4`` = "-translate-x-4"
        let ``-translateX1/2`` = "-translate-x-1/2"
        let ``-translateXFull`` = "-translate-x-full"
        let translateY0 = "translate-y-0"
        let translateY1 = "translate-y-1"
        let translateY2 = "translate-y-2"
        let translateY3 = "translate-y-3"
        let translateY4 = "translate-y-4"
        let translateY5 = "translate-y-5"
        let translateY6 = "translate-y-6"
        let translateY8 = "translate-y-8"
        let translateY10 = "translate-y-10"
        let translateY12 = "translate-y-12"
        let translateY16 = "translate-y-16"
        let translateY20 = "translate-y-20"
        let translateY24 = "translate-y-24"
        let translateY32 = "translate-y-32"
        let translateY40 = "translate-y-40"
        let translateY48 = "translate-y-48"
        let translateY56 = "translate-y-56"
        let translateY64 = "translate-y-64"
        let ``translateY1/2`` = "translate-y-1/2"
        let ``translateY1/3`` = "translate-y-1/3"
        let ``translateY2/3`` = "translate-y-2/3"
        let ``translateY1/4`` = "translate-y-1/4"
        let ``translateY3/4`` = "translate-y-3/4"
        let translateYFull = "translate-y-full"
        let ``-translateY1`` = "-translate-y-1"
        let ``-translateY2`` = "-translate-y-2"
        let ``-translateY4`` = "-translate-y-4"
        let ``-translateY1/2`` = "-translate-y-1/2"
        let ``-translateYFull`` = "-translate-y-full"

    /// skew utilities
    module skew =
        let skewX0 = "skew-x-0"
        let skewX1 = "skew-x-1"
        let skewX2 = "skew-x-2"
        let skewX3 = "skew-x-3"
        let skewX6 = "skew-x-6"
        let skewX12 = "skew-x-12"
        let ``-skewX1`` = "-skew-x-1"
        let ``-skewX2`` = "-skew-x-2"
        let ``-skewX3`` = "-skew-x-3"
        let ``-skewX6`` = "-skew-x-6"
        let ``-skewX12`` = "-skew-x-12"
        let skewY0 = "skew-y-0"
        let skewY1 = "skew-y-1"
        let skewY2 = "skew-y-2"
        let skewY3 = "skew-y-3"
        let skewY6 = "skew-y-6"
        let skewY12 = "skew-y-12"
        let ``-skewY1`` = "-skew-y-1"
        let ``-skewY2`` = "-skew-y-2"
        let ``-skewY3`` = "-skew-y-3"
        let ``-skewY6`` = "-skew-y-6"
        let ``-skewY12`` = "-skew-y-12"

    /// transformOrigin utilities
    module transformOrigin =
        let originCenter = "origin-center"
        let originTop = "origin-top"
        let originTopRight = "origin-top-right"
        let originRight = "origin-right"
        let originBottomRight = "origin-bottom-right"
        let originBottom = "origin-bottom"
        let originBottomLeft = "origin-bottom-left"
        let originLeft = "origin-left"
        let originTopLeft = "origin-top-left"

    /// transition utilities
    module transition =
        let transitionNone = "transition-none"
        let transitionAll = "transition-all"
        let transition = "transition"
        let transitionColors = "transition-colors"
        let transitionOpacity = "transition-opacity"
        let transitionShadow = "transition-shadow"
        let transitionTransform = "transition-transform"

    /// duration utilities
    module duration =
        let duration0 = "duration-0"
        let duration75 = "duration-75"
        let duration100 = "duration-100"
        let duration150 = "duration-150"
        let duration200 = "duration-200"
        let duration300 = "duration-300"
        let duration500 = "duration-500"
        let duration700 = "duration-700"
        let duration1000 = "duration-1000"

    /// ease utilities
    module ease =
        let easeLinear = "ease-linear"
        let easeIn = "ease-in"
        let easeOut = "ease-out"
        let easeInOut = "ease-in-out"

    /// delay utilities
    module delay =
        let delay0 = "delay-0"
        let delay75 = "delay-75"
        let delay100 = "delay-100"
        let delay150 = "delay-150"
        let delay200 = "delay-200"
        let delay300 = "delay-300"
        let delay500 = "delay-500"
        let delay700 = "delay-700"
        let delay1000 = "delay-1000"

    /// animation utilities
    module animation =
        let animateNone = "animate-none"
        let animateSpin = "animate-spin"
        let animatePing = "animate-ping"
        let animatePulse = "animate-pulse"
        let animateBounce = "animate-bounce"

    /// blur utilities
    module blur =
        let blurNone = "blur-none"
        let blurSm = "blur-sm"
        let blur = "blur"
        let blurMd = "blur-md"
        let blurLg = "blur-lg"
        let blurXl = "blur-xl"
        let blur2Xl = "blur-2xl"
        let blur3Xl = "blur-3xl"

    /// brightness utilities
    module brightness =
        let brightness0 = "brightness-0"
        let brightness50 = "brightness-50"
        let brightness75 = "brightness-75"
        let brightness90 = "brightness-90"
        let brightness95 = "brightness-95"
        let brightness100 = "brightness-100"
        let brightness105 = "brightness-105"
        let brightness110 = "brightness-110"
        let brightness125 = "brightness-125"
        let brightness150 = "brightness-150"
        let brightness200 = "brightness-200"

    /// contrast utilities
    module contrast =
        let contrast0 = "contrast-0"
        let contrast50 = "contrast-50"
        let contrast75 = "contrast-75"
        let contrast100 = "contrast-100"
        let contrast125 = "contrast-125"
        let contrast150 = "contrast-150"
        let contrast200 = "contrast-200"

    /// grayscale utilities
    module grayscale =
        let grayscale0 = "grayscale-0"
        let grayscale = "grayscale"

    /// hueRotate utilities
    module hueRotate =
        let hueRotate0 = "hue-rotate-0"
        let hueRotate15 = "hue-rotate-15"
        let hueRotate30 = "hue-rotate-30"
        let hueRotate60 = "hue-rotate-60"
        let hueRotate90 = "hue-rotate-90"
        let hueRotate180 = "hue-rotate-180"
        let ``-hueRotate15`` = "-hue-rotate-15"
        let ``-hueRotate30`` = "-hue-rotate-30"
        let ``-hueRotate60`` = "-hue-rotate-60"
        let ``-hueRotate90`` = "-hue-rotate-90"
        let ``-hueRotate180`` = "-hue-rotate-180"

    /// invert utilities
    module invert =
        let invert0 = "invert-0"
        let invert = "invert"

    /// saturate utilities
    module saturate =
        let saturate0 = "saturate-0"
        let saturate50 = "saturate-50"
        let saturate100 = "saturate-100"
        let saturate150 = "saturate-150"
        let saturate200 = "saturate-200"

    /// sepia utilities
    module sepia =
        let sepia0 = "sepia-0"
        let sepia = "sepia"

    /// dropShadow utilities
    module dropShadow =
        let dropShadowSm = "drop-shadow-sm"
        let dropShadow = "drop-shadow"
        let dropShadowMd = "drop-shadow-md"
        let dropShadowLg = "drop-shadow-lg"
        let dropShadowXl = "drop-shadow-xl"
        let dropShadow2Xl = "drop-shadow-2xl"
        let dropShadowNone = "drop-shadow-none"

    /// backdropBlur utilities
    module backdropBlur =
        let backdropBlurNone = "backdrop-blur-none"
        let backdropBlurSm = "backdrop-blur-sm"
        let backdropBlur = "backdrop-blur"
        let backdropBlurMd = "backdrop-blur-md"
        let backdropBlurLg = "backdrop-blur-lg"
        let backdropBlurXl = "backdrop-blur-xl"
        let backdropBlur2Xl = "backdrop-blur-2xl"
        let backdropBlur3Xl = "backdrop-blur-3xl"

    /// backdropBrightness utilities
    module backdropBrightness =
        let backdropBrightness0 = "backdrop-brightness-0"
        let backdropBrightness50 = "backdrop-brightness-50"
        let backdropBrightness75 = "backdrop-brightness-75"
        let backdropBrightness90 = "backdrop-brightness-90"
        let backdropBrightness95 = "backdrop-brightness-95"
        let backdropBrightness100 = "backdrop-brightness-100"
        let backdropBrightness105 = "backdrop-brightness-105"
        let backdropBrightness110 = "backdrop-brightness-110"
        let backdropBrightness125 = "backdrop-brightness-125"
        let backdropBrightness150 = "backdrop-brightness-150"
        let backdropBrightness200 = "backdrop-brightness-200"

    /// backdropContrast utilities
    module backdropContrast =
        let backdropContrast0 = "backdrop-contrast-0"
        let backdropContrast50 = "backdrop-contrast-50"
        let backdropContrast75 = "backdrop-contrast-75"
        let backdropContrast100 = "backdrop-contrast-100"
        let backdropContrast125 = "backdrop-contrast-125"
        let backdropContrast150 = "backdrop-contrast-150"
        let backdropContrast200 = "backdrop-contrast-200"

    /// backdropGrayscale utilities
    module backdropGrayscale =
        let backdropGrayscale0 = "backdrop-grayscale-0"
        let backdropGrayscale = "backdrop-grayscale"

    /// backdropInvert utilities
    module backdropInvert =
        let backdropInvert0 = "backdrop-invert-0"
        let backdropInvert = "backdrop-invert"

    /// backdropOpacity utilities
    module backdropOpacity =
        let backdropOpacity0 = "backdrop-opacity-0"
        let backdropOpacity5 = "backdrop-opacity-5"
        let backdropOpacity10 = "backdrop-opacity-10"
        let backdropOpacity20 = "backdrop-opacity-20"
        let backdropOpacity25 = "backdrop-opacity-25"
        let backdropOpacity30 = "backdrop-opacity-30"
        let backdropOpacity40 = "backdrop-opacity-40"
        let backdropOpacity50 = "backdrop-opacity-50"
        let backdropOpacity60 = "backdrop-opacity-60"
        let backdropOpacity70 = "backdrop-opacity-70"
        let backdropOpacity75 = "backdrop-opacity-75"
        let backdropOpacity80 = "backdrop-opacity-80"
        let backdropOpacity90 = "backdrop-opacity-90"
        let backdropOpacity95 = "backdrop-opacity-95"
        let backdropOpacity100 = "backdrop-opacity-100"

    /// backdropSaturate utilities
    module backdropSaturate =
        let backdropSaturate0 = "backdrop-saturate-0"
        let backdropSaturate50 = "backdrop-saturate-50"
        let backdropSaturate100 = "backdrop-saturate-100"
        let backdropSaturate150 = "backdrop-saturate-150"
        let backdropSaturate200 = "backdrop-saturate-200"

    /// backdropSepia utilities
    module backdropSepia =
        let backdropSepia0 = "backdrop-sepia-0"
        let backdropSepia = "backdrop-sepia"

    /// cursor utilities
    module cursor =
        let cursorAuto = "cursor-auto"
        let cursorDefault = "cursor-default"
        let cursorPointer = "cursor-pointer"
        let cursorWait = "cursor-wait"
        let cursorText = "cursor-text"
        let cursorMove = "cursor-move"
        let cursorHelp = "cursor-help"
        let cursorNotAllowed = "cursor-not-allowed"
        let cursorNone = "cursor-none"
        let cursorContextMenu = "cursor-context-menu"
        let cursorProgress = "cursor-progress"
        let cursorCell = "cursor-cell"
        let cursorCrosshair = "cursor-crosshair"
        let cursorVerticalText = "cursor-vertical-text"
        let cursorAlias = "cursor-alias"
        let cursorCopy = "cursor-copy"
        let cursorNoDrop = "cursor-no-drop"
        let cursorGrab = "cursor-grab"
        let cursorGrabbing = "cursor-grabbing"
        let cursorAllScroll = "cursor-all-scroll"
        let cursorColResize = "cursor-col-resize"
        let cursorRowResize = "cursor-row-resize"
        let cursorNResize = "cursor-n-resize"
        let cursorEResize = "cursor-e-resize"
        let cursorSResize = "cursor-s-resize"
        let cursorWResize = "cursor-w-resize"
        let cursorNeResize = "cursor-ne-resize"
        let cursorNwResize = "cursor-nw-resize"
        let cursorSeResize = "cursor-se-resize"
        let cursorSwResize = "cursor-sw-resize"
        let cursorEwResize = "cursor-ew-resize"
        let cursorNsResize = "cursor-ns-resize"
        let cursorNeswResize = "cursor-nesw-resize"
        let cursorNwseResize = "cursor-nwse-resize"
        let cursorZoomIn = "cursor-zoom-in"
        let cursorZoomOut = "cursor-zoom-out"

    /// pointerEvents utilities
    module pointerEvents =
        let pointerEventsNone = "pointer-events-none"
        let pointerEventsAuto = "pointer-events-auto"

    /// resize utilities
    module resize =
        let resizeNone = "resize-none"
        let resize = "resize"
        let resizeY = "resize-y"
        let resizeX = "resize-x"

    /// userSelect utilities
    module userSelect =
        let selectNone = "select-none"
        let selectText = "select-text"
        let selectAll = "select-all"
        let selectAuto = "select-auto"

    /// touchAction utilities
    module touchAction =
        let touchAuto = "touch-auto"
        let touchNone = "touch-none"
        let touchPanX = "touch-pan-x"
        let touchPanLeft = "touch-pan-left"
        let touchPanRight = "touch-pan-right"
        let touchPanY = "touch-pan-y"
        let touchPanUp = "touch-pan-up"
        let touchPanDown = "touch-pan-down"
        let touchPinchZoom = "touch-pinch-zoom"
        let touchManipulation = "touch-manipulation"

    /// scrollBehavior utilities
    module scrollBehavior =
        let scrollAuto = "scroll-auto"
        let scrollSmooth = "scroll-smooth"

    /// scrollSnapAlign utilities
    module scrollSnapAlign =
        let snapStart = "snap-start"
        let snapEnd = "snap-end"
        let snapCenter = "snap-center"
        let snapAlignNone = "snap-align-none"

    /// scrollSnapStop utilities
    module scrollSnapStop =
        let snapNormal = "snap-normal"
        let snapAlways = "snap-always"

    /// scrollSnapType utilities
    module scrollSnapType =
        let snapNone = "snap-none"
        let snapX = "snap-x"
        let snapY = "snap-y"
        let snapBoth = "snap-both"
        let snapMandatory = "snap-mandatory"
        let snapProximity = "snap-proximity"

    /// willChange utilities
    module willChange =
        let willChangeAuto = "will-change-auto"
        let willChangeScroll = "will-change-scroll"
        let willChangeContents = "will-change-contents"
        let willChangeTransform = "will-change-transform"

    /// appearance utilities
    module appearance =
        let appearanceNone = "appearance-none"
        let appearanceAuto = "appearance-auto"

    /// caretColor utilities
    module caretColor =
        let caretInherit = "caret-inherit"
        let caretCurrent = "caret-current"
        let caretTransparent = "caret-transparent"
        let caretBlack = "caret-black"
        let caretWhite = "caret-white"
        let caretSlate500 = "caret-slate-500"
        let caretGray500 = "caret-gray-500"
        let caretRed500 = "caret-red-500"
        let caretOrange500 = "caret-orange-500"
        let caretYellow500 = "caret-yellow-500"
        let caretGreen500 = "caret-green-500"
        let caretBlue500 = "caret-blue-500"
        let caretIndigo500 = "caret-indigo-500"
        let caretPurple500 = "caret-purple-500"
        let caretPink500 = "caret-pink-500"

    /// accentColor utilities
    module accentColor =
        let accentInherit = "accent-inherit"
        let accentCurrent = "accent-current"
        let accentTransparent = "accent-transparent"
        let accentBlack = "accent-black"
        let accentWhite = "accent-white"
        let accentAuto = "accent-auto"
        let accentSlate500 = "accent-slate-500"
        let accentGray500 = "accent-gray-500"
        let accentRed500 = "accent-red-500"
        let accentOrange500 = "accent-orange-500"
        let accentYellow500 = "accent-yellow-500"
        let acretGreen500 = "accent-green-500"
        let accentBlue500 = "accent-blue-500"
        let accentIndigo500 = "accent-indigo-500"
        let accentPurple500 = "accent-purple-500"
        let accentPink500 = "accent-pink-500"

    /// fill utilities
    module fill =
        let fillNone = "fill-none"
        let fillInherit = "fill-inherit"
        let fillCurrent = "fill-current"
        let fillTransparent = "fill-transparent"
        let fillBlack = "fill-black"
        let fillWhite = "fill-white"
        let fillSlate50 = "fill-slate-50"
        let fillSlate100 = "fill-slate-100"
        let fillSlate200 = "fill-slate-200"
        let fillSlate300 = "fill-slate-300"
        let fillSlate400 = "fill-slate-400"
        let fillSlate500 = "fill-slate-500"
        let fillSlate600 = "fill-slate-600"
        let fillSlate700 = "fill-slate-700"
        let fillSlate800 = "fill-slate-800"
        let fillSlate900 = "fill-slate-900"
        let fillGray500 = "fill-gray-500"
        let fillRed500 = "fill-red-500"
        let fillOrange500 = "fill-orange-500"
        let fillYellow500 = "fill-yellow-500"
        let fillGreen500 = "fill-green-500"
        let fillBlue500 = "fill-blue-500"
        let fillIndigo500 = "fill-indigo-500"
        let fillPurple500 = "fill-purple-500"
        let fillPink500 = "fill-pink-500"

    /// stroke utilities
    module stroke =
        let strokeNone = "stroke-none"
        let strokeInherit = "stroke-inherit"
        let strokeCurrent = "stroke-current"
        let strokeTransparent = "stroke-transparent"
        let strokeBlack = "stroke-black"
        let strokeWhite = "stroke-white"
        let strokeSlate500 = "stroke-slate-500"
        let strokeGray500 = "stroke-gray-500"
        let strokeRed500 = "stroke-red-500"
        let strokeOrange500 = "stroke-orange-500"
        let strokeYellow500 = "stroke-yellow-500"
        let strokeGreen500 = "stroke-green-500"
        let strokeBlue500 = "stroke-blue-500"
        let strokeIndigo500 = "stroke-indigo-500"
        let strokePurple500 = "stroke-purple-500"
        let strokePink500 = "stroke-pink-500"

    /// strokeWidth utilities
    module strokeWidth =
        let stroke0 = "stroke-0"
        let stroke1 = "stroke-1"
        let stroke2 = "stroke-2"

    /// borderCollapse utilities
    module borderCollapse =
        let borderCollapse = "border-collapse"
        let borderSeparate = "border-separate"

    /// borderSpacing utilities
    module borderSpacing =
        let borderSpacing0 = "border-spacing-0"
        let borderSpacing1 = "border-spacing-1"
        let borderSpacing2 = "border-spacing-2"
        let borderSpacing3 = "border-spacing-3"
        let borderSpacing4 = "border-spacing-4"
        let borderSpacing5 = "border-spacing-5"
        let borderSpacing6 = "border-spacing-6"
        let borderSpacing8 = "border-spacing-8"
        let borderSpacing10 = "border-spacing-10"
        let borderSpacing12 = "border-spacing-12"
        let borderSpacingX0 = "border-spacing-x-0"
        let borderSpacingX1 = "border-spacing-x-1"
        let borderSpacingX2 = "border-spacing-x-2"
        let borderSpacingX4 = "border-spacing-x-4"
        let borderSpacingY0 = "border-spacing-y-0"
        let borderSpacingY1 = "border-spacing-y-1"
        let borderSpacingY2 = "border-spacing-y-2"
        let borderSpacingY4 = "border-spacing-y-4"

    /// tableLayout utilities
    module tableLayout =
        let tableAuto = "table-auto"
        let tableFixed = "table-fixed"

    /// captionSide utilities
    module captionSide =
        let captionTop = "caption-top"
        let captionBottom = "caption-bottom"

    /// objectFit utilities
    module objectFit =
        let objectContain = "object-contain"
        let objectCover = "object-cover"
        let objectFill = "object-fill"
        let objectNone = "object-none"
        let objectScaleDown = "object-scale-down"

    /// objectPosition utilities
    module objectPosition =
        let objectBottom = "object-bottom"
        let objectCenter = "object-center"
        let objectLeft = "object-left"
        let objectLeftBottom = "object-left-bottom"
        let objectLeftTop = "object-left-top"
        let objectRight = "object-right"
        let objectRightBottom = "object-right-bottom"
        let objectRightTop = "object-right-top"
        let objectTop = "object-top"

    /// overscrollBehavior utilities
    module overscrollBehavior =
        let overscrollAuto = "overscroll-auto"
        let overscrollContain = "overscroll-contain"
        let overscrollNone = "overscroll-none"
        let overscrollXAuto = "overscroll-x-auto"
        let overscrollXContain = "overscroll-x-contain"
        let overscrollXNone = "overscroll-x-none"
        let overscrollYAuto = "overscroll-y-auto"
        let overscrollYContain = "overscroll-y-contain"
        let overscrollYNone = "overscroll-y-none"

    /// columns utilities
    module columns =
        let columns1 = "columns-1"
        let columns2 = "columns-2"
        let columns3 = "columns-3"
        let columns4 = "columns-4"
        let columns5 = "columns-5"
        let columns6 = "columns-6"
        let columns7 = "columns-7"
        let columns8 = "columns-8"
        let columns9 = "columns-9"
        let columns10 = "columns-10"
        let columns11 = "columns-11"
        let columns12 = "columns-12"
        let columnsAuto = "columns-auto"
        let columnsXs = "columns-xs"
        let columnsSm = "columns-sm"
        let columnsMd = "columns-md"
        let columnsLg = "columns-lg"
        let columnsXl = "columns-xl"
        let columns2Xl = "columns-2xl"
        let columns3Xl = "columns-3xl"

    /// breakAfter utilities
    module breakAfter =
        let breakAfterAuto = "break-after-auto"
        let breakAfterAvoid = "break-after-avoid"
        let breakAfterAll = "break-after-all"
        let breakAfterAvoidPage = "break-after-avoid-page"
        let breakAfterPage = "break-after-page"
        let breakAfterLeft = "break-after-left"
        let breakAfterRight = "break-after-right"
        let breakAfterColumn = "break-after-column"

    /// breakBefore utilities
    module breakBefore =
        let breakBeforeAuto = "break-before-auto"
        let breakBeforeAvoid = "break-before-avoid"
        let breakBeforeAll = "break-before-all"
        let breakBeforeAvoidPage = "break-before-avoid-page"
        let breakBeforePage = "break-before-page"
        let breakBeforeLeft = "break-before-left"
        let breakBeforeRight = "break-before-right"
        let breakBeforeColumn = "break-before-column"

    /// breakInside utilities
    module breakInside =
        let breakInsideAuto = "break-inside-auto"
        let breakInsideAvoid = "break-inside-avoid"
        let breakInsideAvoidPage = "break-inside-avoid-page"
        let breakInsideAvoidColumn = "break-inside-avoid-column"

    /// boxDecorationBreak utilities
    module boxDecorationBreak =
        let boxDecorationClone = "box-decoration-clone"
        let boxDecorationSlice = "box-decoration-slice"

    /// boxSizing utilities
    module boxSizing =
        let boxBorder = "box-border"
        let boxContent = "box-content"
        let floatStart = "float-start"
        let floatEnd = "float-end"
        let floatRight = "float-right"
        let floatLeft = "float-left"
        let floatNone = "float-none"

    /// clear utilities
    module clear =
        let clearStart = "clear-start"
        let clearEnd = "clear-end"
        let clearLeft = "clear-left"
        let clearRight = "clear-right"
        let clearBoth = "clear-both"
        let clearNone = "clear-none"

    /// isolation utilities
    module isolation =
        let isolate = "isolate"
        let isolationAuto = "isolation-auto"

    /// flexBasis utilities
    module flexBasis =
        let basis0 = "basis-0"
        let basis1 = "basis-1"
        let basis2 = "basis-2"
        let basis3 = "basis-3"
        let basis4 = "basis-4"
        let basis5 = "basis-5"
        let basis6 = "basis-6"
        let basis8 = "basis-8"
        let basis10 = "basis-10"
        let basis12 = "basis-12"
        let basis16 = "basis-16"
        let basis20 = "basis-20"
        let basis24 = "basis-24"
        let basis32 = "basis-32"
        let basis40 = "basis-40"
        let basis48 = "basis-48"
        let basis56 = "basis-56"
        let basis64 = "basis-64"
        let basisAuto = "basis-auto"
        let basisFull = "basis-full"
        let ``basis1/2`` = "basis-1/2"
        let ``basis1/3`` = "basis-1/3"
        let ``basis2/3`` = "basis-2/3"
        let ``basis1/4`` = "basis-1/4"
        let ``basis3/4`` = "basis-3/4"

    /// order utilities
    module order =
        let orderFirst = "order-first"
        let orderLast = "order-last"
        let orderNone = "order-none"
        let order1 = "order-1"
        let order2 = "order-2"
        let order3 = "order-3"
        let order4 = "order-4"
        let order5 = "order-5"
        let order6 = "order-6"
        let order7 = "order-7"
        let order8 = "order-8"
        let order9 = "order-9"
        let order10 = "order-10"
        let order11 = "order-11"
        let order12 = "order-12"

    /// alignContent utilities
    module alignContent =
        let contentNormal = "content-normal"
        let contentCenter = "content-center"
        let contentStart = "content-start"
        let contentEnd = "content-end"
        let contentBetween = "content-between"
        let contentAround = "content-around"
        let contentEvenly = "content-evenly"
        let contentBaseline = "content-baseline"
        let contentStretch = "content-stretch"

    /// alignSelf utilities
    module alignSelf =
        let selfAuto = "self-auto"
        let selfStart = "self-start"
        let selfEnd = "self-end"
        let selfCenter = "self-center"
        let selfStretch = "self-stretch"
        let selfBaseline = "self-baseline"

    /// justifySelf utilities
    module justifySelf =
        let justifySelfAuto = "justify-self-auto"
        let justifySelfStart = "justify-self-start"
        let justifySelfEnd = "justify-self-end"
        let justifySelfCenter = "justify-self-center"
        let justifySelfStretch = "justify-self-stretch"

    /// placeContent utilities
    module placeContent =
        let placeContentCenter = "place-content-center"
        let placeContentStart = "place-content-start"
        let placeContentEnd = "place-content-end"
        let placeContentBetween = "place-content-between"
        let placeContentAround = "place-content-around"
        let placeContentEvenly = "place-content-evenly"
        let placeContentBaseline = "place-content-baseline"
        let placeContentStretch = "place-content-stretch"

    /// placeItems utilities
    module placeItems =
        let placeItemsStart = "place-items-start"
        let placeItemsEnd = "place-items-end"
        let placeItemsCenter = "place-items-center"
        let placeItemsBaseline = "place-items-baseline"
        let placeItemsStretch = "place-items-stretch"

    /// placeSelf utilities
    module placeSelf =
        let placeSelfAuto = "place-self-auto"
        let placeSelfStart = "place-self-start"
        let placeSelfEnd = "place-self-end"
        let placeSelfCenter = "place-self-center"
        let placeSelfStretch = "place-self-stretch"

    /// gridAutoFlow utilities
    module gridAutoFlow =
        let gridFlowRow = "grid-flow-row"
        let gridFlowCol = "grid-flow-col"
        let gridFlowDense = "grid-flow-dense"
        let gridFlowRowDense = "grid-flow-row-dense"
        let gridFlowColDense = "grid-flow-col-dense"

    /// gridAutoColumns utilities
    module gridAutoColumns =
        let autoColsAuto = "auto-cols-auto"
        let autoColsMin = "auto-cols-min"
        let autoColsMax = "auto-cols-max"
        let autoColsFr = "auto-cols-fr"

    /// gridAutoRows utilities
    module gridAutoRows =
        let autoRowsAuto = "auto-rows-auto"
        let autoRowsMin = "auto-rows-min"
        let autoRowsMax = "auto-rows-max"
        let autoRowsFr = "auto-rows-fr"

    /// gridRows utilities
    module gridRows =
        let ``rows-none`` = "grid-rows-none"
        let ``rows-1`` = "grid-rows-1"
        let ``rows-2`` = "grid-rows-2"
        let ``rows-3`` = "grid-rows-3"
        let ``rows-4`` = "grid-rows-4"
        let ``rows-5`` = "grid-rows-5"
        let ``rows-6`` = "grid-rows-6"
        let ``rows-7`` = "grid-rows-7"
        let ``rows-8`` = "grid-rows-8"
        let ``rows-9`` = "grid-rows-9"
        let ``rows-10`` = "grid-rows-10"
        let ``rows-11`` = "grid-rows-11"
        let ``rows-12`` = "grid-rows-12"
        let rowsSubgrid = "grid-rows-subgrid"

    /// colStart utilities
    module colStart =
        let colStartAuto = "col-start-auto"
        let colStart1 = "col-start-1"
        let colStart2 = "col-start-2"
        let colStart3 = "col-start-3"
        let colStart4 = "col-start-4"
        let colStart5 = "col-start-5"
        let colStart6 = "col-start-6"
        let colStart7 = "col-start-7"
        let colStart8 = "col-start-8"
        let colStart9 = "col-start-9"
        let colStart10 = "col-start-10"
        let colStart11 = "col-start-11"
        let colStart12 = "col-start-12"
        let colStart13 = "col-start-13"

    /// colEnd utilities
    module colEnd =
        let colEndAuto = "col-end-auto"
        let colEnd1 = "col-end-1"
        let colEnd2 = "col-end-2"
        let colEnd3 = "col-end-3"
        let colEnd4 = "col-end-4"
        let colEnd5 = "col-end-5"
        let colEnd6 = "col-end-6"
        let colEnd7 = "col-end-7"
        let colEnd8 = "col-end-8"
        let colEnd9 = "col-end-9"
        let colEnd10 = "col-end-10"
        let colEnd11 = "col-end-11"
        let colEnd12 = "col-end-12"
        let colEnd13 = "col-end-13"

    /// rowStart utilities
    module rowStart =
        let rowStartAuto = "row-start-auto"
        let rowStart1 = "row-start-1"
        let rowStart2 = "row-start-2"
        let rowStart3 = "row-start-3"
        let rowStart4 = "row-start-4"
        let rowStart5 = "row-start-5"
        let rowStart6 = "row-start-6"
        let rowStart7 = "row-start-7"
        let rowStart8 = "row-start-8"
        let rowStart9 = "row-start-9"
        let rowStart10 = "row-start-10"
        let rowStart11 = "row-start-11"
        let rowStart12 = "row-start-12"
        let rowStart13 = "row-start-13"

    /// rowEnd utilities
    module rowEnd =
        let rowEndAuto = "row-end-auto"
        let rowEnd1 = "row-end-1"
        let rowEnd2 = "row-end-2"
        let rowEnd3 = "row-end-3"
        let rowEnd4 = "row-end-4"
        let rowEnd5 = "row-end-5"
        let rowEnd6 = "row-end-6"
        let rowEnd7 = "row-end-7"
        let rowEnd8 = "row-end-8"
        let rowEnd9 = "row-end-9"
        let rowEnd10 = "row-end-10"
        let rowEnd11 = "row-end-11"
        let rowEnd12 = "row-end-12"
        let rowEnd13 = "row-end-13"

    /// backgroundAttachment utilities
    module backgroundAttachment =
        let bgFixed = "bg-fixed"
        let bgLocal = "bg-local"
        let bgScroll = "bg-scroll"

    /// backgroundClip utilities
    module backgroundClip =
        let bgClipBorder = "bg-clip-border"
        let bgClipPadding = "bg-clip-padding"
        let bgClipContent = "bg-clip-content"
        let bgClipText = "bg-clip-text"

    /// backgroundOrigin utilities
    module backgroundOrigin =
        let bgOriginBorder = "bg-origin-border"
        let bgOriginPadding = "bg-origin-padding"
        let bgOriginContent = "bg-origin-content"

    /// backgroundPosition utilities
    module backgroundPosition =
        let bgBottom = "bg-bottom"
        let bgCenter = "bg-center"
        let bgLeft = "bg-left"
        let bgLeftBottom = "bg-left-bottom"
        let bgLeftTop = "bg-left-top"
        let bgRight = "bg-right"
        let bgRightBottom = "bg-right-bottom"
        let bgRightTop = "bg-right-top"
        let bgTop = "bg-top"

    /// backgroundRepeat utilities
    module backgroundRepeat =
        let bgRepeat = "bg-repeat"
        let bgNoRepeat = "bg-no-repeat"
        let bgRepeatX = "bg-repeat-x"
        let bgRepeatY = "bg-repeat-y"
        let bgRepeatRound = "bg-repeat-round"
        let bgRepeatSpace = "bg-repeat-space"

    /// backgroundSize utilities
    module backgroundSize =
        let bgAuto = "bg-auto"
        let bgCover = "bg-cover"
        let bgContain = "bg-contain"

    /// backgroundImage utilities
    module backgroundImage =
        let bgNone = "bg-none"
        let bgGradientToT = "bg-gradient-to-t"
        let bgGradientToTr = "bg-gradient-to-tr"
        let bgGradientToR = "bg-gradient-to-r"
        let bgGradientToBr = "bg-gradient-to-br"
        let bgGradientToB = "bg-gradient-to-b"
        let bgGradientToBl = "bg-gradient-to-bl"
        let bgGradientToL = "bg-gradient-to-l"
        let bgGradientToTl = "bg-gradient-to-tl"

    /// gradientColorStops utilities
    module gradientColorStops =
        let fromInherit = "from-inherit"
        let fromCurrent = "from-current"
        let fromTransparent = "from-transparent"
        let fromBlack = "from-black"
        let fromWhite = "from-white"
        let fromSlate50 = "from-slate-50"
        let fromSlate100 = "from-slate-100"
        let fromSlate200 = "from-slate-200"
        let fromSlate300 = "from-slate-300"
        let fromSlate400 = "from-slate-400"
        let fromSlate500 = "from-slate-500"
        let fromSlate600 = "from-slate-600"
        let fromSlate700 = "from-slate-700"
        let fromSlate800 = "from-slate-800"
        let fromSlate900 = "from-slate-900"
        let fromBlue500 = "from-blue-500"
        let fromRed500 = "from-red-500"
        let fromGreen500 = "from-green-500"
        let fromYellow500 = "from-yellow-500"
        let fromPurple500 = "from-purple-500"
        let fromPink500 = "from-pink-500"
        let viaInherit = "via-inherit"
        let viaCurrent = "via-current"
        let viaTransparent = "via-transparent"
        let viaBlack = "via-black"
        let viaWhite = "via-white"
        let viaSlate500 = "via-slate-500"
        let viaBlue500 = "via-blue-500"
        let viaRed500 = "via-red-500"
        let viaGreen500 = "via-green-500"
        let viaPurple500 = "via-purple-500"
        let toInherit = "to-inherit"
        let toCurrent = "to-current"
        let toTransparent = "to-transparent"
        let toBlack = "to-black"
        let toWhite = "to-white"
        let toSlate50 = "to-slate-50"
        let toSlate100 = "to-slate-100"
        let toSlate200 = "to-slate-200"
        let toSlate300 = "to-slate-300"
        let toSlate400 = "to-slate-400"
        let toSlate500 = "to-slate-500"
        let toSlate600 = "to-slate-600"
        let toSlate700 = "to-slate-700"
        let toSlate800 = "to-slate-800"
        let toSlate900 = "to-slate-900"
        let toBlue500 = "to-blue-500"
        let toRed500 = "to-red-500"
        let toGreen500 = "to-green-500"
        let toYellow500 = "to-yellow-500"
        let toPurple500 = "to-purple-500"
        let toPink500 = "to-pink-500"

    /// mixBlendMode utilities
    module mixBlendMode =
        let mixBlendNormal = "mix-blend-normal"
        let mixBlendMultiply = "mix-blend-multiply"
        let mixBlendScreen = "mix-blend-screen"
        let mixBlendOverlay = "mix-blend-overlay"
        let mixBlendDarken = "mix-blend-darken"
        let mixBlendLighten = "mix-blend-lighten"
        let mixBlendColorDodge = "mix-blend-color-dodge"
        let mixBlendColorBurn = "mix-blend-color-burn"
        let mixBlendHardLight = "mix-blend-hard-light"
        let mixBlendSoftLight = "mix-blend-soft-light"
        let mixBlendDifference = "mix-blend-difference"
        let mixBlendExclusion = "mix-blend-exclusion"
        let mixBlendHue = "mix-blend-hue"
        let mixBlendSaturation = "mix-blend-saturation"
        let mixBlendColor = "mix-blend-color"
        let mixBlendLuminosity = "mix-blend-luminosity"
        let mixBlendPlusDarker = "mix-blend-plus-darker"
        let mixBlendPlusLighter = "mix-blend-plus-lighter"

    /// backgroundBlendMode utilities
    module backgroundBlendMode =
        let bgBlendNormal = "bg-blend-normal"
        let bgBlendMultiply = "bg-blend-multiply"
        let bgBlendScreen = "bg-blend-screen"
        let bgBlendOverlay = "bg-blend-overlay"
        let bgBlendDarken = "bg-blend-darken"
        let bgBlendLighten = "bg-blend-lighten"
        let bgBlendColorDodge = "bg-blend-color-dodge"
        let bgBlendColorBurn = "bg-blend-color-burn"
        let bgBlendHardLight = "bg-blend-hard-light"
        let bgBlendSoftLight = "bg-blend-soft-light"
        let bgBlendDifference = "bg-blend-difference"
        let bgBlendExclusion = "bg-blend-exclusion"
        let bgBlendHue = "bg-blend-hue"
        let bgBlendSaturation = "bg-blend-saturation"
        let bgBlendColor = "bg-blend-color"
        let bgBlendLuminosity = "bg-blend-luminosity"

    /// screenReaders utilities
    module screenReaders =
        let srOnly = "sr-only"
        let notSrOnly = "not-sr-only"

    /// forcedColorAdjust utilities
    module forcedColorAdjust =
        let forcedColorAdjustAuto = "forced-color-adjust-auto"
        let forcedColorAdjustNone = "forced-color-adjust-none"

